add:purchases関連作成
quest-academia/yanbaru_ec_traning pull request #10
Opened 2020-11-23 13:12 UTC by takumi-isd

2020-11-24 09:18 UTC, ryota100 reviewed
お疲れ様です。
１点だけ、コロンの後のスペースという点だけ指摘させていただきました。
その他マイグレーションファイルとシーダーファイルについても問題ありません。
以上、よろしくお願い致します🤲

2020-11-24 09:18 UTC, ryota100 commented on database/migrations/2020_11_23_031335_create_purchases_table.php
> +            $table->string('purchase_company',128);
今回の共同開発は、PSR-2というコーディング規約に乗っ取っています。
（以前、PDFでSlackに記載した資料にも書かれています）
コーディング規約参考資料：https://www.ritolab.com/entry/92

規約上、「,」カンマの後ろには、スペースを１つ入れるのがルールとなっておりますので、
こちらを修正ください。
他は、スペースが入っておりましたのでこちらだけ修正ください✨

2020-11-24 13:42 UTC, SekiYukihiro requested changes
お疲れ様でした！

綺麗に書けていて素晴らしいと思います😊

ただ、今回は必ず起こるのですが、
コンフリクトが発生していますので
コンフリクトを解消して、もう一度プルリク しましょう。

難しいと思いますが、やってみてください☺️

2020-11-25 23:55 UTC, ryota100 commented
指摘していた点の修正確認いたしました😊
よろしくお願いします。

2020-11-26 14:53 UTC, SekiYukihiro approved these changes
OKです！
よくかけていると思います✨

ただ、プルリク 投げるときは、下記のURLをこちらに添付するようにして下さい！
宜しくお願いします。
https://github.com/quest-academia/yanbaru_ec_traning/pull/10

2020-11-26 14:53 UTC, SekiYukihiro commented
OKです！
よくかけていると思います✨

マージしました！

ただ、プルリク 投げるときは、下記のURLをこちらに添付するようにして下さい！
宜しくお願いします。
https://github.com/quest-academia/yanbaru_ec_traning/pull/10

2020-11-26 14:53 UTC, merged