Feature/riki/seeder purchases
quest-academia/yanbaru_ec_traning pull request #100
Opened 2021-03-20 12:22 UTC by riki-ichikawa

シーダーファイル作成しましたので、レビューよろしくお願い致します。

2021-03-20 14:41 UTC, ziko7110 commented on database/seeds/PurchasesTableSeeder.php
> +            'purchase_price' => '10000',
integerで定義したカラムに関してはINT型でデータを入れたほうがいいと思います。
'10000'はだと文字列なのかな？と考えてしまいます。（PHPはこれでも上手いこと動いてくれる言語ですけどね。。。）
なので''を削除でお願いします。

2021-03-20 14:41 UTC, ziko7110 commented on database/seeds/PurchasesTableSeeder.php
> +            'purchase_date' => Carbon::now(),
Carbon::now(),はnow()でも動きます！（こちらは補足なので修正しなくて大丈夫です^^）

2021-03-20 23:57 UTC, riki-ichikawa commented on database/migrations/2021_03_15_140001_create_m_user_classifications_table.php
> +<?php
ファイル作成時間を調整しました。
中身は変更していません。

2021-03-21 00:00 UTC, riki-ichikawa commented on database/migrations/2021_03_15_140001_create_m_user_classifications_table.php
> +        Schema::dropIfExists('m_user_classifications');
ファイル作成時間を調整しました。
中身は変更していません。

2021-03-21 00:01 UTC, riki-ichikawa commented on database/migrations/2021_03_15_140001_create_m_user_classifications_table.php
> +}
ファイル作成時間を調整しました。
中身は変更していません。

2021-03-21 00:03 UTC, riki-ichikawa commented on database/migrations/2021_03_15_140002_create_m_users_table.php
> +            $table->integer('user_classification_id')->unsigned(); //ユーザ種別 ->unsigned()追加
ファイル作成時間を調整しました。
unsigned()を追加しました。

2021-03-21 00:03 UTC, riki-ichikawa commented on database/seeds/PurchasesTableSeeder.php
> +            'purchase_price' => '10000',
ご指摘有難うございます。
integerで定義したカラムのデータをINT型に修正しました。
（これでも動いてしまうので、気づかず通ってしまうのは少し怖いですね。。。）

2021-03-21 00:10 UTC, riki-ichikawa commented on database/seeds/PurchasesTableSeeder.php
> +            'purchase_date' => Carbon::now(),
ご指摘有難うございます。
修正は無でいきますが、now()に変更しても動くこと確認できました。

質問なのですが、carbon::now()とnow()であれば、now()を使用した方が良いのでしょうか。

2021-03-21 00:23 UTC, ziko7110 commented on database/seeds/PurchasesTableSeeder.php
> +            'purchase_price' => '10000',
型定義をしっかりしないとダメな言語もあるので、今のうちに意識出来るといいですね！＾＾

2021-03-21 00:26 UTC, ziko7110 commented on database/seeds/PurchasesTableSeeder.php
> +            'purchase_date' => Carbon::now(),
PHPの関数としてnow()があり上位互換で Carbonクラスがある感じですね！
難しいことはCarbon推奨ですが、useでクラスを読み込む必要があるので簡単なものはPHP関数使ったほうが記述量が少なくなるというメリットがあります。

2021-03-21 00:52 UTC, shimotaroo requested changes
このプルリクはpurchasesテーブル用のシーダーファイル作成のものだと思いますが、purchasesテーブル作成用のマイグレーションファイル（`database/migrations/2021_03_18_130637_create_purchases_table.php`）も含まれてしまっていますね。。

加えて、

- カラム名がproducts_idになっている
- 外部キー制約用のコードが入ってない

ので（修正前の状態）、おそらく、マイグレーションファイル作成用のブランチからこのブランチを切ってしまっているような気がしますが、どのようにブランチを切っていますか？

解決方法としては、

```
git checkout develop-5term
git pull origin develop-5term
git checkout feature/riki/seederPurchases
git merge develop-5term
```

してもう一度pushしていただけると解決するかと思います！

一度状況を確認・整理してください🙇‍♂️

2021-03-21 08:05 UTC, riki-ichikawa commented
ご指摘有難うございます。

なぜこうなってしまったのか状況整理しました。
結論としては、ゆうたろーさんのご指摘通り、マイグレーション作成用のブランチからこのブランチを切ってしまっていました。
アドバイス頂いた方法実施しましたので内容ご確認お願い致します。

以下、今回develop-5termをpullした後に実施した内容です。

１、既に完成しているマイグレーションファイルがあるのに新たに作成してしまった以下マイグレーションファイルを削除しました。
purchasesテーブル作成用のマイグレーションファイル（database/migrations/2021_03_18_130637_create_purchases_table.php）


２、ユーザー関連のマイグレーションファイルに関して、
develop-5termをpullした際に、以下４つのファイルがある状態になったため、
（１）と（２）を削除しました。今回ファイル名を編集した（３）と（４）は残しました。

（１）2021_03_15_140102_create_m_users_table.php
（２）2021_03_15_140200_create_m_user_classifications_table.php 
（３）2021_03_15_140001_create_m_user_classifications_table.php（自分が今回ファイル名編集）
（４）2021_03_15_140002_create_m_users_table.php（自分が今回ファイル名編集）

2021-03-21 12:03 UTC, shimotaroo requested changes
LGTMです〜🥰
マージします！！

2021-03-21 12:04 UTC, shimotaroo approved these changes

2021-03-21 12:54 UTC, merged