フロント ログイン画面作成しました。
quest-academia/yanbaru_ec_traning pull request #105
Opened 2021-03-27 09:11 UTC by KawataTsutomu

お疲れ様です。
composer部分の変更は取り込んでしまって良いのか分からず2回に分けてコミットしました。
レビューお願いいたします。

2021-03-28 13:24 UTC, ziko7110 commented on composer.json
> +        "laravelcollective/html": "5.8.*"
"laravelcollective/html": "5.8.*"
こちらを削除して再度
composer install
してみて下さい＾＾
,の扱いが注意です

2021-03-28 13:24 UTC, ziko7110 commented on resources/views/auth/login.blade.php
> +      {!! Form::open(['route' => 'login.post']) !!}
<form>への変更をお願い致します！

2021-03-28 13:24 UTC, ziko7110 commented on resources/views/auth/login.blade.php
> +                  {!! Form::email('email', old('email'), ['class' => 'form-control']) !!}
バリデーションメッセージが、出ないと思うので確認をお願い致します！

2021-03-30 21:27 UTC, KawataTsutomu commented
- Laravelcollectiveインストールしてしまったので composer.jsonを修正してcomposer再インストール

- エラーメッセージ表示させるようにlogin.blade.php変更しました。

よろしくお願いします。

2021-03-31 05:13 UTC, ziko7110 commented on resources/views/auth/login.blade.php
> +                        <div class="row justify-content-center">
インデントの見直しをお願い致します！

2021-03-31 22:32 UTC, ziko7110 commented on resources/views/auth/login.blade.php
> +                    <div class="row justify-content-center">
ここもインデントをお願いします！

2021-04-01 12:01 UTC, KawataTsutomu commented
すいません見落としていました…
インデント修正しました。
よろしくお願いします。

2021-04-01 12:28 UTC, ziko7110 commented on resources/views/auth/login.blade.php
> +        {{ Form::open(['route' => 'login.post']) }}
ここはlaravelcollectiveを使用したいのか一行下<form>を使用したいのかわからないです。

2021-04-02 02:11 UTC, shimotaroo requested changes
レビューしました！
インデントだけ揃えて完成させましょう！！

2021-04-02 02:11 UTC, shimotaroo commented on resources/views/auth/login.blade.php
> +            <form method="POST" action="{{ route('login') }}">
ここはインデント揃えておきましょう！

2021-04-02 02:11 UTC, shimotaroo commented on resources/views/auth/login.blade.php
> +            </form>
インデントは1段</main>側に移動させましょう。

2021-04-02 14:17 UTC, KawataTsutomu commented
レビューありがとうございます！
インデント修正しました。
ご確認お願いします。

2021-04-03 00:08 UTC, shimotaroo approved these changes
LGTMです！
お疲れ様です😁
インデント、気をつけていきましょう🔥

2021-04-03 00:08 UTC, merged