ユーザ情報確認画面実装
quest-academia/yanbaru_ec_traning pull request #108
Opened 2021-04-06 20:10 UTC by KawataTsutomu

お疲れ様です。
ユーザー情報確認画面実装しました。
確認お願いいたします。

2021-04-07 11:10 UTC, ziko7110 commented on resources/views/auth/user_info.blade.php
> +        <form method="POST" action="{{ route('user_info') }}">
ここはなぜ、formタグを使用したのですか？

2021-04-07 15:39 UTC, KawataTsutomu commented on resources/views/auth/user_info.blade.php
> +        <form method="POST" action="{{ route('user_info') }}">
ログイン画面作成の流れで書いてしまっていました。
入力、送信ではないですね...

2021-04-07 15:44 UTC, KawataTsutomu commented
お疲れ様です。
user_info.blade.php修正しました。
ご確認お願いいたします。

2021-04-07 23:36 UTC, ziko7110 commented on app/Http/Controllers/UserController.php
> +    public function index()
使用してないメソッドは消して置きましょう＾＾
user周りの機能は使用するControllerが多いのでチームの皆が混同ないためです！

2021-04-08 09:41 UTC, KawataTsutomu commented
お疲れ様です。
UserController.php修正（使っていないメソッドを削除）しました。
ご確認お願いします。

2021-04-08 12:45 UTC, shimotaroo requested changes
ほぼLGTMです😆

コメント入れました！
1箇所だけ修正しておきましょう！

2021-04-08 12:45 UTC, shimotaroo commented on resources/views/auth/user_info.blade.php
> +                    <p class="contents-text">{{ $user->id }}</p>
`{{ $user->id }}`だけ両側に半角スペースが入ってますね。
今回は修正不要ですが、自分で書くコードにいは統一性を持たせましょう！

ちなみに僕は両側に半角スペース入れて書いてます。

2021-04-08 12:45 UTC, shimotaroo commented on routes/web.php
> +Route::get('/user_info', 'UserController@show')->name('user_info');
`->name('user_info')`
ですが、ここも他のコードと書き方を揃えましょう！
どう修正すれば良いか考えてみましょう！

https://readouble.com/laravel/5.7/ja/routing.html

2021-04-09 13:47 UTC, KawataTsutomu commented
レビューありがとうございます。
web.php修正しました。
書き方統一するよう意識していきます。
ご確認お願いいたします。

2021-04-09 14:37 UTC, shimotaroo approved these changes
LGTMです👍👍👍👍👍👍👍👍

2021-04-09 14:37 UTC, merged