ユーザー情報編集画面実装
quest-academia/yanbaru_ec_traning pull request #109
Opened 2021-04-11 21:35 UTC by KawataTsutomu

お疲れ様です。
ユーザー情報画面実装完了しましたのでレビューお願いいたします。

クリックで画面移動できるように変更したため

- login.blade.php

- user_info.blade.php
も変更しています。

2021-04-12 10:49 UTC, ziko7110 commented on app/Http/Controllers/UserController.php
> +        return view('auth/user_edit', ['user' => $user]);
慣れてきたら、短く出来ないか？など考えてみて下さいね＾＾！

```PHP
return view('auth.user_edit', ['user' => Auth::user()]);
```

2021-04-12 10:49 UTC, ziko7110 commented on app/Http/Controllers/UserController.php
> +    public function update(Request $request, User $user)
Auth::user();とupdate(Request $request, User $user)の$userは同じものでしょうか？
同じなら、どちらかだけで良いかと思います。

2021-04-12 10:49 UTC, ziko7110 commented on resources/views/auth/user_edit.blade.php
> +                            <div class="row justify-content-center">
インデントをお願いします！

2021-04-12 10:49 UTC, ziko7110 commented on resources/views/auth/user_edit.blade.php
> +<!-- @extends('layouts.app') -->
これはコメントアウトですか？

2021-04-12 10:49 UTC, ziko7110 commented on routes/web.php
> +Route::get('/user_edit', 'UserController@edit')->name('user.edit');
Auth::user()でユーザー情報は取れるのいいのですが、本来はクエリストリングでidを送るものだと覚えていてくださいね！（意図的にやってたら素晴らしいです。）
```
Route::get('/user_edit/{id}', 'UserController@edit')->name('user.edit');
```

2021-04-13 14:44 UTC, KawataTsutomu commented on app/Http/Controllers/UserController.php
> +    public function update(Request $request, User $user)
同じだったのでupdate(Request $request, User $user)の$user消します！

2021-04-13 15:22 UTC, KawataTsutomu commented on routes/web.php
> +Route::get('/user_edit', 'UserController@edit')->name('user.edit');
理解せずやっていたので復習しておきます。

2021-04-13 15:23 UTC, KawataTsutomu commented
レビューありがとうございます。
インデント、UserController修正しました。
ご確認お願いします。

2021-04-14 00:01 UTC, shimotaroo requested changes
レビューいたしました！
いくつか修正依頼・質問を記載しておりますので少し考えてみてください！

2021-04-14 00:01 UTC, shimotaroo commented on app/Http/Controllers/UserController.php
> +        ]);
POST時のバリデーションはフォームリクエストに切り離してみましょう！
https://readouble.com/laravel/5.8/ja/validation.html

2021-04-15 14:22 UTC, KawataTsutomu commented on app/Http/Controllers/UserController.php
> +    public function edit(User $user)
`$user = Auth::user();`
$userはログインしているuserと書いているから必要ない

2021-04-15 14:37 UTC, KawataTsutomu commented on app/Http/Controllers/UserController.php
> +    public function delete(Request $request)
情報を保存する方法をググったときに
```
$user->fill($request->input());
$user->save();
```
で保存できると見つけて、インプット部分を保存するようrequestするのに使うイメージで使っていました。

2021-04-16 16:52 UTC, KawataTsutomu commented
お疲れ様です。
フォームリクエストにバリデーション切り離し完了しました。
確認お願いいたします。

2021-04-16 21:24 UTC, KawataTsutomu commented on app/Http/Controllers/UserController.php
> +    public function delete(Request $request)
上と一緒でいらないですね💦

2021-04-17 00:59 UTC, ziko7110 commented on resources/views/auth/user_edit.blade.php
> +                                @if ($errors->has('last_name'))
インデントを下げすぎてないでしょうか！

2021-04-17 00:59 UTC, ziko7110 commented on resources/views/auth/user_edit.blade.php
> +                                @endif
@if　が下げすぎてるのですが、閉じタグあたりを違和感に思えるとすぐにインデントのミスに気づけるようになると思います！

2021-04-17 00:59 UTC, ziko7110 commented on app/Http/Requests/StoreBlogPost.php
> +class StoreBlogPost extends FormRequest
BlogRequestのようなクラス名が良いですね。
Requestを付けておけば、明示的にリクエストクラスということがわかるので！
逆に、storeでrequestクラスを呼ぶことがほとんどなこととその場合はPOST送信でなので、こちらは命名に不要です！

2021-04-17 14:55 UTC, KawataTsutomu commented on resources/views/auth/user_edit.blade.php
> +                                @endif
閉じタグ意識してみます！

2021-04-17 14:57 UTC, KawataTsutomu commented on app/Http/Requests/StoreBlogPost.php
> +class StoreBlogPost extends FormRequest
何も考えずつけてしまっていました。
処理をイメージできるようなクラス名意識していきます！

2021-04-17 15:06 UTC, KawataTsutomu commented
お疲れ様です。
インスタンス、クラス名修正しました。
ご確認お願いいたします。

2021-04-18 01:47 UTC, ziko7110 approved these changes

2021-04-18 01:54 UTC, merged