add:商品検索画面(Riki)
quest-academia/yanbaru_ec_traning pull request #110
Opened 2021-04-12 08:28 UTC by riki-ichikawa

商品検索画面の作成完了しましたので、レビューお願い致します。

2021-04-12 11:03 UTC, ziko7110 commented on app/Models/Product.php
> +    public function productCategory(){
「{」前にスペースをお願いします！一度PSR-2の規則などを見直して見て下さい＾＾
http://www.infiniteloop.co.jp/docs/psr/psr-2-coding-style-guide.html
```
public function productCategory() {
        return $this->belongsTo('App\Models\ProductCategory', 'category_id', 'id');
    }
```

2021-04-12 11:03 UTC, ziko7110 commented on resources/views/products/search_products.blade.php
> +                @foreach ($products_details as $product_details)
ここはインデントを一つ上げて下さい。

2021-04-13 09:19 UTC, riki-ichikawa commented on app/Http/Controllers/ProductsController.php
> +        if ($request->product_name && $request->product_category){
アドバイスありがとうございます。
->when()の使い方調べて、反映させてみました。
ご確認お願い致します。

2021-04-13 09:20 UTC, riki-ichikawa commented on app/Models/Product.php
> +    public function productCategory(){
確認不足で申し訳ございません。
コード規約を確認し修正致しました。

2021-04-13 09:21 UTC, riki-ichikawa commented on resources/views/products/search_products.blade.php
> +                @foreach ($products_details as $product_details)
確認不足で申し訳ございません。
インデント修正致しました。

2021-04-13 09:22 UTC, riki-ichikawa commented on resources/views/products/search_products.blade.php
> +                  <td>{{$product_details->product_name}}</td>
確認不足で申し訳ございません。
スペース追加しました。

2021-04-13 09:23 UTC, riki-ichikawa commented on routes/web.php
> +Route::get('products', 'ProductsController@index');
他ルーティング同様、nameを追加しました。

2021-04-17 11:03 UTC, riki-ichikawa commented on resources/views/products/search_products.blade.php
> -   <main>
インデントが２つになっていた部分を４つに修正しました。

2021-04-21 05:06 UTC, riki-ichikawa commented on app/Http/Controllers/ProductDetailsController.php
> +    public function show($id)
商品検索画面→商品詳細画面の遷移修正
showメソッドに変更しています。

2021-04-21 05:06 UTC, riki-ichikawa commented on app/Http/Controllers/ProductDetailsController.php
> -    //削除予定(仮データで処理)
商品検索画面→商品詳細画面の遷移修正
仮データを削除。

2021-04-21 05:11 UTC, riki-ichikawa commented on app/Http/Controllers/ProductsController.php
> +        $products_details = Product::with('Category')
Joinメソッド→withメソッドへ変更しています。
変更前の場合、'm_products'テーブルの「id」が'm_categories'テーブルの「id」で上書きされてしまうことに気づいたため修正しました。

2021-04-21 05:13 UTC, riki-ichikawa commented on app/Http/Controllers/ProductsController.php
> +use App\Models\Category;
Model：Categoryが既に作成済でマージされていたため、自分で作成していたModel：ProductCategoryを削除しました。

2021-04-21 05:14 UTC, riki-ichikawa commented on app/Models/Product.php
> +    public function product_status()
スペルミス修正

2021-04-21 05:15 UTC, riki-ichikawa commented on public/css/styles.css
> +
不足分追加しました。

2021-04-21 05:18 UTC, riki-ichikawa commented on routes/web.php
> +Route::get('products/{id}', 'ProductDetailsController@show')->name('product.show');
画面定義書通りに修正しました。

2021-04-23 06:16 UTC, shimotaroo requested changes
レビューしました！

数点コメントしていますのでご確認お願いします！
もう少しですね😊

2021-04-23 06:16 UTC, shimotaroo commented on app/Http/Controllers/ProductsController.php
> +use App\Models\Category;
ここ1行空けるのが一般的です！

2021-04-23 06:16 UTC, shimotaroo commented on app/Http/Controllers/ProductsController.php
> +        $products_details = Product::with('Category')
`->with()`メソッドの使い方を間違えているのでこちらのドキュメントを見ながら修正してみてください！
https://readouble.com/laravel/5.8/ja/eloquent-relationships.html#eager-loading

今回、変数名はスネークケースに統一していましたっけ？
他のファイルではキャメルケースになっていました。ご確認ください！

2021-04-23 06:16 UTC, shimotaroo commented on app/Http/Controllers/ProductsController.php
> +        $all_products_categories = Category::get();
【要確認】
変数名の書き方

2021-04-23 09:13 UTC, riki-ichikawa commented on app/Http/Controllers/ProductsController.php
> +use App\Models\Category;
ご指摘ありがとうございます。
１行空けるよう修正します。

2021-04-23 09:43 UTC, riki-ichikawa commented on app/Http/Controllers/ProductsController.php
> +        $all_products_categories = Category::get();
指摘内容の意図として、以下と考えたので変数名をcategoriesに修正します。
１、商品コントローラ内に記載するのでall_productsのように詳細に書く必要はない。
（２、キャメルケースに統一する。）

見当違いであれば、ご指摘お願い致します。

2021-04-23 09:45 UTC, riki-ichikawa commented on app/Http/Controllers/ProductsController.php
> +        $products_details = Product::with('Category')
ご指摘ありがとうございます。

１、ご指摘いただいたwith()メソッドの使い方ですが、()内に「Product モデルの categoryメソッド名」を記載するという修正であっていますでしょうか？
以下に修正しようと考えています。
＜修正コード＞
　$products = Product::with('category')

２、申し訳ございません、変数名に関してはキャメルケースで統一でした。
　　他全て修正します。

2021-04-23 23:16 UTC, shimotaroo commented on app/Http/Controllers/ProductsController.php
> +        $products_details = Product::with('Category')
完璧です！！！！！！！
素晴らしいです😆

2021-04-23 23:16 UTC, shimotaroo commented on app/Http/Controllers/ProductsController.php
> +        $all_products_categories = Category::get();
>　１、商品コントローラ内に記載するのでall_productsのように詳細に書く必要はない。

これに関しては変数名は丁寧につけて問題ないですよ。
なので、キャメルケースに変更するだけで良いです。

コントローラー名を省略するのはメソッドですね。
`ProductsController.php`ならわざわざ`getProducts`ではなくて`get`で意味わかるよね、って感じです！

2021-04-24 00:20 UTC, riki-ichikawa commented on app/Http/Controllers/ProductsController.php
> +        $products_details = Product::with('Category')
ありがとうございます。
上記コメント通り修正しました。

2021-04-24 00:23 UTC, riki-ichikawa commented on app/Http/Controllers/ProductsController.php
> +        $all_products_categories = Category::get();
ご回答ありがとうございます。
今回キャメルケースに変更しました。
コントローラのメソッド名に関してはおっしゃる通りですね。
今後気をつけてみます。

2021-04-24 00:24 UTC, riki-ichikawa commented on app/Http/Controllers/ProductDetailsController.php
> +        $categoryName = Category::find($product->category_id);
変数名をキャメルケースに変更
$category_name→categoryName

2021-04-24 00:25 UTC, riki-ichikawa commented on app/Http/Controllers/ProductsController.php
> +use App\Models\Category;
８行目追加しました。

2021-04-24 00:27 UTC, riki-ichikawa commented on app/Http/Controllers/ProductsController.php
> +        $allProductsCategories = Category::get();
変数名をキャメルケースに変更
$all_products_categories→$allProductsCategories

2021-04-24 00:28 UTC, riki-ichikawa commented on app/Http/Controllers/ProductsController.php
> +        $productsDetails = Product::with('category')
１、with()の使用方法修正

２、変数名をキャメルケースに変更
　　$products_details→$productsDetails

2021-04-24 04:03 UTC, shimotaroo approved these changes
LGTMです😁
ちゃんとご自分で調べて正しい実装もできて、本当に素晴らしいですね！！
お疲れ様でした！

2021-04-24 04:03 UTC, merged