add:注文履歴画面（Riki）
quest-academia/yanbaru_ec_traning pull request #116
Opened 2021-04-21 08:23 UTC by riki-ichikawa

注文履歴画面完了しましたのでレビューお願い致します。

2021-04-21 08:37 UTC, riki-ichikawa commented on database/seeds/M_Shipment_StatusesTableSeeder.php
> +            ]
前回MTGで話のあった通り、注文状態は準備中、キャンセル、発送済の３パターンに変更しました。

2021-04-21 11:09 UTC, ziko7110 commented on app/Http/Controllers/OrdersController.php
> +        if ($request->input('term_flg') == "false") {
これでif文も省略出来ないでしょうか？？

```
->when(($request->term_flag !== false) , function ($query) {
                            return $query->where('order_date',  '>', (Carbon::now()->subMonth(3)));
                        })

```

2021-04-21 15:02 UTC, riki-ichikawa commented on app/Http/Controllers/OrdersController.php
> +
ご指摘ありがとうございます。
不要な改行削除します。

2021-04-21 15:08 UTC, riki-ichikawa commented on app/Http/Controllers/OrdersController.php
> +        $months_before = Carbon::now()->subMonth($set_term_month);
ご指摘の通り、When内でしか使用していないため、上記のように修正します。
１５〜１７行目が不要になるので、短くすることができますね。

2021-04-21 16:06 UTC, riki-ichikawa commented on app/Http/Controllers/OrdersController.php
> +        if ($request->input('term_flg') == "false") {
ご指摘ありがとうございます。
この部分に関して、whenメソッドを使用して省略できないと考えています。
３ヶ月ボタン or 全件表示ボタンの画面表示する時に、
コントローラーで$term_flg＝'true' or 'false'として、Viewに渡していますが、
if文を省略してしまうと$term_flgが未定義でエラーとなってしまいます。

if文でやりたいことは同じで、以下の書き方で少し省略できて良いと考えたのですが、
どうでしょうか。

$term_flg = $request->input('term_flg') == 'false' ? false : true;

頂いたアドバイスの意図と見当違いの回答であれば、再度ご指摘頂きたくお願いします。

2021-04-21 23:56 UTC, ziko7110 commented on app/Http/Controllers/OrdersController.php
> +        if ($request->input('term_flg') == "false") {
bladeまで、変数を送っているのを見落としてました。
抜けない判定でしたね！汗
参考演算子もflag系なら良いと思います！！

2021-04-21 23:56 UTC, ziko7110 commented on app/Http/Controllers/OrdersController.php
> +            foreach ($order_info->orderDetails as $order_details) {
foreachで取り出した、oder_deitailって複数のshipment_status_idを持っているのでしょうか？
shipment_statusが複数のoder_deitailに割り振られてると思うので、2回目のforeachが不要のように思いました。

2021-04-22 04:39 UTC, riki-ichikawa commented on app/Http/Controllers/OrdersController.php
> +            foreach ($order_info->orderDetails as $order_details) {
$order_detailsは複数のshipment_status_idは持っていません。

複雑ですが、下記のようになっており、やはりforeachを２回まわさないといけないのかと考えています。
（説明が上手くできず申し訳ございません。）

$orders_detailsは複数の$order_infoを持つ。（1人のユーザが複数注文している場合、$orders_detailsには複数の注文詳細 $order_infoを持つ。）
1つの$order_infoには、複数の’orderDetails’と1つの’users’を持っている。（一つの注文詳細 $order_infoには複数の商品詳細 orderDetailsとユーザ情報 usersを持つ）
1つの’orderDetails’の中にshipment_status_idが一つある。（一商品詳細 orderDetailsには発送状態 shipment_status_idを持つ）

→現在のコードの説明
　１つめのforeachで複数注文に対して、１つ１つの注文を持ってくる。
　２つめのforeachで１つの注文の中にある複数商品情報に対して、一つ一つの商品情報を持ってくる。
　商品情報の発送状態が準備中か判断する。
　１つの注文にある複数商品のなかで、一つでも準備中のものがあれば、準備中フラグをtrueにする。

2021-04-22 05:56 UTC, riki-ichikawa commented on resources/views/order/order_history.blade.php
> +                                        <td class="col-2 px-0 text-center" id="order_number_1">{{ $order_info->id }}</td>
注文詳細番号を表示する箇所ですが、間違えて$order_info->idとなっていますので、修正します。

一点確認ですが、ER図で注文テーブルに注文詳細番号カラムがなく、商品詳細テーブルに注文詳細番号カラムが有ります。
注文テーブルと注文詳細テーブルは注文IDで紐づいており、同じ注文IDの商品詳細テーブルには全て同じ注文詳細番号となります。
そのため、現在のER図で商品詳細テーブルにある注文詳細番号カラムは注文テーブルにあるべきではないかと考えています。注文テーブルではなく、注文詳細テーブルにある理由が有りましたら教えて頂きたく、お願い致します。

2021-04-22 13:59 UTC, ziko7110 commented on app/Http/Controllers/OrdersController.php
> +        $orders_details = Order::where('user_id', Auth::id())
下記の用に書いて頂けると、リレーションのテーブルが追いやすいです！
```
foreach ($orders as $order) {
    foreach ($order->orderDetails as $order_detail) {
        if ($order_detail->shipment_status_id == "1") {
            $shipment_status_flg = true;
            break;
        }
    }
}
```

2021-04-23 02:21 UTC, riki-ichikawa commented on resources/views/order/order_history.blade.php
> +                                            </td>
商品詳細テーブルにある商品詳細番号を全て表示させる形にしています。

2021-04-23 02:29 UTC, riki-ichikawa commented on resources/views/order/order_history.blade.php
> +                                            </td>
注文IDを表示となっていたため、商品詳細番号を表示に変更しています。

2021-04-23 02:30 UTC, riki-ichikawa commented on app/Http/Controllers/OrdersController.php
> +        $orders_details = Order::where('user_id', Auth::id())
アドバイスありがとうございます。
上記のように修正致しました。

2021-04-23 02:36 UTC, riki-ichikawa commented on resources/views/order/order_history.blade.php
> +                                        <td class="col-2 px-0 text-center" id="order_number_1">{{ $order_info->id }}</td>
→申し訳ございません。本件、勘違いしていました。
　同じ注文IDでも商品によって注文詳細番号が違うため、１つの注文に対して複数の注文詳細番号がある場合がある。
　そのため、注文詳細番号を全て表示する形に修正しました。

2021-04-25 00:59 UTC, riki-ichikawa commented on resources/views/order/order_history.blade.php
> +                                                {{ $order->orderDetails[0]->order_detail_number }}
１つの注文に対して複数の異なる注文詳細番号があると考えていましたが、同じ注文には全て同じ注文詳細番号ということなので、１つの注文に対して複数ある注文詳細の一つ目の注文詳細番号のみ表示する形に変更しています。

2021-04-25 01:03 UTC, riki-ichikawa commented on resources/views/order/order_history.blade.php
> +                                        <!-- <td class="col-2 px-0 text-center"><a href="{{ route('order.detail', ['id' => $order->id,'productCategory' => $order->orderDetails[0]->order_detail_number
注文詳細画面への遷移部分追加しました。

2021-04-25 01:17 UTC, ziko7110 commented on resources/views/order/order_history.blade.php
> +                                                {{ $order->orderDetails[0]->order_detail_number }}
ここの解釈が難しいですね。。
設計の部分についてしっかり考えれるようになってて素晴らしいです！

2021-04-25 04:11 UTC, shimotaroo requested changes
レビューしました！

リレーションメソッド名の修正だけお願いします！

2021-04-25 04:11 UTC, shimotaroo commented on app/Http/Controllers/OrdersController.php
> +                if ($order_detail->shipment_status_id == "1") {//shipment_status_id = 1 は 注文状態：'準備中'
（今回は修正不要です）

比較する1が文字列と型も決まっているなら
`==`ではなく`===`（厳密比較）の方が良いなと思いました！

2021-04-25 04:11 UTC, shimotaroo commented on app/Models/Order.php
> +    }
`belongsTo`であればメソッド名は単数形`user`にすべきですね！

参考：https://readouble.com/laravel/6.x/ja/eloquent-relationships.html#one-to-many#one-to-many-inverse

2021-04-25 04:11 UTC, shimotaroo commented on app/Models/OrderDetail.php
> +    }
app/Models/Order.php同様

2021-04-25 04:24 UTC, riki-ichikawa commented on app/Http/Controllers/OrdersController.php
> +                if ($order_detail->shipment_status_id == "1") {//shipment_status_id = 1 は 注文状態：'準備中'
ご指摘ありがとうございます。

厳密比較の方がいいですね。今後気をつけます。

2021-04-25 04:27 UTC, riki-ichikawa commented on app/Models/Order.php
> +    }
ご指摘ありがとうございます。

belongsToなので単数形が正しいですね。修正いたしました。
メソッド名の単数形、複数形も注意します。

2021-04-25 04:28 UTC, riki-ichikawa commented on app/Models/OrderDetail.php
> +    }
app/Models/Order.php同様、メソッド名を単数形に修正致しました。

2021-04-25 10:58 UTC, riki-ichikawa commented on resources/views/order/order_history.blade.php
> +                                        <!-- <td class="col-2 px-0 text-center"><a href="{{ route('order.detail', ['id' => $order->id,'orderDetailNumber' => $order->orderDetails[0]->order_detail_numb
変数名が正しくなかったので、修正しました。
productCategory　→　orderDetailNumber

2021-04-25 12:53 UTC, shimotaroo approved these changes
LGTMです😁
お疲れ様でした！！

2021-04-25 12:53 UTC, merged