バック商品追加画面（なかむー）
quest-academia/yanbaru_ec_traning pull request #117
Opened 2021-04-22 21:26 UTC by nakasan773

バック商品追加画面の実装完了しました。
レビューのほどよろしくお願い致します。

2021-04-22 21:36 UTC, nakasan773 commented on public/css/styles.css
> +
商品詳細画面作成時に抜けていた部分です。

2021-04-22 21:56 UTC, nakasan773 commented on resources/views/products/newAdd.blade.php
> +                                @endforeach
すみません、未選択時のバリデーション忘れていました。
修正しましたら再度レビューお願い致します。

2021-04-22 22:40 UTC, nakasan773 commented
プルリク後なのにたくさん修正してしまい、申し訳ありません...。
よろしくお願い致します。

2021-04-22 23:48 UTC, ziko7110 commented on app/Http/Controllers/AddController.php
> +    public function store(Request $request)
「フォームリクエスト」を作成してみましょう＾＾！
https://qiita.com/sakuraya/items/abca057a424fa9b5a187

2021-04-22 23:48 UTC, ziko7110 commented on app/Http/Controllers/AddController.php
> +
下記の用に書くと、ちょっと実装が楽になります！
 
 ```
   public function index(Request $request)
    {
        return view('products.newAdd', [
                  'categories' => Auth::user(),
                   'user', => Category::all(),
                   'sales', => ProductStatus::all(),
                    'products_status' => Sale::all(),
         ]);
```

シンプルなところは逆compact関数いらなかったりします！＾＾
compact(

2021-04-23 15:39 UTC, nakasan773 commented on app/Http/Controllers/AddController.php
> +
簡素化致しました！

2021-04-23 15:42 UTC, nakasan773 commented on app/Http/Controllers/AddController.php
> +    public function store(Request $request)
フォームリクエストにてバリデーション作成してみました。

2021-04-24 03:43 UTC, ziko7110 commented on app/Http/Controllers/AddController.php
> +      public function index(Request $request)
インデントがずれてるようです！

2021-04-24 03:43 UTC, ziko7110 commented on app/Http/Controllers/AddController.php
> +    public function store(StoreProduct $request)
ProductRequestsのような名前の方が分かり易いです！
基本的にフォームリクエストはstoreがupdateでしか基本的に呼ばれないので名前には不要です！
モデルやユースケースクラスも似たような呼び出し方をするので、Requestと明示的になってると分かりやすいです！

2021-04-24 03:43 UTC, ziko7110 commented on app/Http/Requests/StoreProduct.php
> +        'price' => ['required'],
数字はinteger制約などあるといいですね！

2021-04-24 03:43 UTC, ziko7110 commented on app/Models/Product.php
> +<<<<<<< HEAD
コンフリクト解決時に生まれたと思うですが不要なので消してください
```
<<<<<<< HEAD
や
=======
```

2021-04-24 16:29 UTC, nakasan773 commented on app/Models/Product.php
> +<<<<<<< HEAD
解消しました。

2021-04-24 16:32 UTC, nakasan773 commented on app/Http/Requests/StoreProduct.php
> +        'price' => ['required'],
バリデーションルール変更致しました。

2021-04-24 16:35 UTC, nakasan773 commented on app/Http/Controllers/AddController.php
> +    public function store(StoreProduct $request)
了解しました！
ProductRequestsに変更しています。

2021-04-24 16:37 UTC, nakasan773 commented on app/Http/Controllers/AddController.php
> +      public function index(Request $request)
インデント修正しました！

2021-04-25 12:51 UTC, shimotaroo requested changes
バリデーションの消し忘れだけ修正をお願いします！！

2021-04-25 12:51 UTC, shimotaroo commented on app/Http/Controllers/AddController.php
> +        $validated = $request->validated();
ここだけ削除してください！

2021-04-25 12:51 UTC, shimotaroo commented on app/Http/Controllers/AddController.php
> +<?php
（今回は修正不要です）

ファイル名の話になりますが、
`AddController.php`という命名はあまりよくないかなと思っています。

`Add`だけだと「何を」追加するためのコントローラーなのかがわかりません。
こういうところも今後意識してみましょう！！

2021-04-25 17:36 UTC, nakasan773 commented on app/Http/Controllers/AddController.php
> +<?php
たしかにそうですね...
実務で気をつけたいと思います！

2021-04-25 17:36 UTC, nakasan773 commented on app/Http/Controllers/AddController.php
> +        $validated = $request->validated();
削除しました。

2021-04-25 17:51 UTC, nakasan773 commented on routes/web.php
> +Route::get('newAdd', 'AddController@index')->name('newAdd.index');
マージされた商品詳細画面のルーティング{id}の影響？で表示できなくなっていたので
newAddに変更しました。

2021-04-26 04:19 UTC, shimotaroo approved these changes
LGTMです😁
お疲れ様でした！

2021-04-26 04:19 UTC, merged