Feature/kawata/order detail show
quest-academia/yanbaru_ec_traning pull request #119
Opened 2021-04-27 16:18 UTC by KawataTsutomu

お疲れ様です。
注文詳細画面完了しました。
・注文履歴画面
ordersController.php　19行目　'users'　を　'user'に修正

order_history.blade.php　38、40~42、45~46行目 　'users'　を　'user'に修正
　　　　　　　　　　　 58~59行目を削除（注文詳細画面用コード）
力さんから依頼を受け一緒に変更してあります。

ご確認お願いいたします。

2021-04-28 10:35 UTC, ziko7110 commented on app/Http/Controllers/OrderDetailController.php
> +
こちらの改行を削除お願いします！

2021-04-28 10:35 UTC, ziko7110 commented on app/Http/Controllers/OrderDetailController.php
> +        ->select('order_detail_number')
インデントこのあたりにも入れて欲しいです＾＾

2021-04-28 10:35 UTC, ziko7110 commented on app/Http/Controllers/OrderDetailController.php
> +        $orderNumber = OrderDetail::whereHas('orders', function ($query) use($id) {
ここの変数名は$orderDetailの方がいいですね！

2021-04-28 10:35 UTC, ziko7110 commented on routes/web.php
> +Route::resource('/orders', 'OrderDetailController', ['only' =>['show','edit']]);
スペースをお願いします！
```PHP
Route::resource('/orders', 'OrderDetailController', ['only' => ['show', 'edit']]);
```

2021-04-28 10:35 UTC, ziko7110 commented on app/Http/Controllers/OrderDetailController.php
> +        $ordersHistory = OrderDetail::with('Product.category','shipmentStatues')
,の後にスペースをお願いします！

2021-04-29 07:04 UTC, KawataTsutomu commented
レビューありがとうございます。
インデント、スペース、変数名修正しました。
ご確認お願いいたします。

2021-04-29 07:11 UTC, KawataTsutomu commented
レビューありがとうございます。
インデント、スペース、変数名修正しました。
ご確認お願いいたします。

2021-04-29 07:31 UTC, KawataTsutomu commented
すいません💦
注文キャンセルしたときの画面遷移できていませんでしたので修正しました。

2021-04-29 11:11 UTC, ziko7110 commented on resources/views/order/order_detail.blade.php
> +        <div class="container py-3">
インデントをお願いします！

2021-04-29 11:11 UTC, ziko7110 commented on app/Http/Controllers/OrderDetailController.php
> +        $userInfo = User::find(Auth::id());
```
User::find(Auth::id());
```
は
```
Auth::user(); 
```
で取得出来ます＾＾

2021-04-29 15:19 UTC, KawataTsutomu commented on app/Http/Controllers/OrderDetailController.php
> +            ->where('shipment_status_id',  '=', '1')
数字です...
修正します！

2021-04-29 15:41 UTC, KawataTsutomu commented
お疲れ様です。
インデント、変数修正しました。
ご確認お願いします🙇‍♂️

2021-04-30 23:16 UTC, shimotaroo requested changes
レビューしました！
いくつか質問していますので教えて欲しいです！

2021-04-30 23:16 UTC, shimotaroo commented on app/Http/Controllers/OrderDetailController.php
> +            ->update(['shipment_status_id' => 2]);
ここもマジックナンバーになっていますね！

2021-04-30 23:16 UTC, shimotaroo commented on app/Http/Controllers/OrderDetailController.php
> +            ->where('shipment_status_id',  '=', 1)
ここ、カンマの後のスペースが大きく見えるのでご確認ください！

2021-04-30 23:16 UTC, shimotaroo commented on app/Models/OrderDetail.php
> +    public function orders() {
ここ`orders`に変えた理由は何ですか？？

2021-04-30 23:16 UTC, shimotaroo commented on app/Models/OrderDetail.php
> +    public function shipmentStatues() {
`shipmentStatues`という名前にした理由はありますか？？

2021-04-30 23:16 UTC, shimotaroo commented on resources/views/order/order_history.blade.php
> +                                        <!-- <td class="col-2 px-0 text-center"><button class="btn btn-primary btn-sm">詳細</button></td> -->
ここは今後使うのでコメントアウトしている感じでしょうか？
不要ならば消しましょう！
これもこの記事に書いています！
https://yutaro-blog.net/2021/04/27/programming-code/

2021-04-30 23:16 UTC, shimotaroo commented on routes/web.php
> +Route::post('newProduct', 'AddController@store')->name('newProduct.post');
`/orders`とか`newProduct`のようにスラッシュが入っていたり入ってなかったりしているのは揃えた方が良いです！
これ、混ぜた理由はありますか？

2021-05-01 13:52 UTC, KawataTsutomu commented on routes/web.php
> +Route::post('newProduct', 'AddController@store')->name('newProduct.post');
混ぜた理由はないので無しで統一します！

2021-05-01 15:13 UTC, KawataTsutomu commented on app/Models/OrderDetail.php
> +    public function orders() {
すいません確認します。

2021-05-01 15:13 UTC, KawataTsutomu commented on app/Models/OrderDetail.php
> +    public function shipmentStatues() {
すいません確認します。

2021-05-02 02:31 UTC, KawataTsutomu commented on app/Models/OrderDetail.php
> +    public function shipmentStatues() {
意識せず書いていました...
複数形、単数形意識していきます。

2021-05-02 02:34 UTC, KawataTsutomu commented
お疲れ様です。
定数定義、メソッド名変更しました。
ご確認お願いいたします。

2021-05-02 03:51 UTC, shimotaroo approved these changes
LGTMです！
マジックナンバーも無くなって良いコードになりましたね😁
お疲れ様でした！！

2021-05-02 03:51 UTC, merged