add:DB構築products関連 migrate&seeder_file作成実行（加藤）
quest-academia/yanbaru_ec_traning pull request #12
Opened 2020-11-23 14:07 UTC by yoshitaro-yoyo

お世話になっております。
products関連のmigrate&seeder_file作成実行しました。
「,」後の半角スペース、各テーブルのPKを「id」へ統一など他の方へのプルリク返答を見て先に行いました。
migration&seeding の成功確認済みです。
　
間での細かいコミットは主に半角スペース関連の修正となります。解りづらくて申し訳有りません。

また「2020_11_23_101254_create_m_products_table.php」のファイルにコメントを多く記載しています。
後々にみて解るようにと書いたのですが、多すぎる様に思い他人からは見づらいのでは?と感じています。
一応共同開発者の方々から見て、「わかり易さ・冗長にならない」ようなバランスと自分にも解るように意識して書きました。
（一度説明することを前提してます）

ご指摘あれば宜しくお願いします。

2020-11-23 14:07 UTC, yoshitaro-yoyo commented on database/migrations/2020_11_23_101254_create_m_products_table.php
> +    public function up()
これがコメントを多数記述したファイルです。
改行などで見やすいようにはしているのですが、肝心のコードが追い辛い様に感じます。
アドバイスお願いします。

2020-11-23 14:26 UTC, yoshitaro-yoyo commented on database/migrations/2020_11_23_101254_create_m_products_table.php
> +
これがコメントを多数記述したファイルです。
改行などで見やすいようにはしているのですが、肝心のコードが追い辛い様に感じます。
アドバイスお願いします。

2020-11-24 15:54 UTC, shimotaroo approved these changes
レビューしました！
全体的にしっかり書けていますね！
コメントの付け方だと意識してみてください😄

2020-11-24 15:54 UTC, shimotaroo commented on database/migrations/2020_11_23_101254_create_m_products_table.php
>              $table->integer('product_status_id')->unsigned()->index();;
$table->integer('sale_status_id')->unsigned()->index();;
$table->integer('product_status_id')->unsigned()->index();;

;が2つ付いてしまっています！

2020-11-24 15:54 UTC, shimotaroo commented on database/migrations/2020_11_23_101254_create_m_products_table.php
>              $table->char('delete_flag')->length(1);
$table->char('delete_flag')->length(1);
は
$table->char('delete_flag', 1);

この書き方でも良いと思います！

2020-11-24 15:54 UTC, shimotaroo commented on database/migrations/2020_11_23_101254_create_m_products_table.php
>              /* CASCADE=親テーブルのレコードに対し、削除または更新を行うと、子テーブル内で同じ値を持つカラムのデータに対して削除または更新を行う */
外部キー制約はしっかり書けていて良いですね👍

2020-11-25 22:37 UTC, yuto-ono commented on database/seeds/DatabaseSeeder.php
> +            ]);
20行目のインデントがずれているので修正お願いします！
（１つ左に）

2020-11-25 22:39 UTC, yuto-ono commented on database/seeds/M_CategoriesTableSeeder.php
> +        ]);
この辺、インデントがスペース１つになっているので修正お願いします！
（コーディング規約上はスペース４つです）

2020-11-25 22:41 UTC, yuto-ono commented on database/seeds/M_ProductsTableSeeder.php
> +        ]);
こちらも同じく、インデントをスペース４つに直しましょう！

2020-11-25 22:43 UTC, yuto-ono commented on database/seeds/M_Products_StatusesTableSeeder.php
> +       ]);
全体的にインデントがずれているので見直して修正しましょう！

2020-11-25 22:43 UTC, yuto-ono commented on database/seeds/M_Sales_StatusesTableSeeder.php
> +        ]);
こちらも同じく、インデントをスペース４つに直しましょう！

2020-11-26 13:45 UTC, shimotaroo commented
確認しました！
修正内容はOKです👍

ただ、コンフリクトしちゃってますね！

2020-12-01 12:21 UTC, yuto-ono commented
まだインデントが直っていません。
全体をよく見て、インデントがおかしい箇所がないか、再度確認しましょう！
あと、コンフリクトが発生していますが、解消の仕方はわかりますか？

2020-12-01 12:22 UTC, yuto-ono requested changes

2020-12-01 12:22 UTC, yuto-ono commented on database/seeds/M_CategoriesTableSeeder.php
> +             'id' => 1,
[]の中身がまだインデントがずれているので直しましょう！

2020-12-01 12:22 UTC, yuto-ono commented on database/seeds/M_ProductsTableSeeder.php
> +            'id' => 1,
[]の中身がまだインデントがずれているので直しましょう！

2020-12-01 12:22 UTC, yuto-ono commented on database/seeds/M_Products_StatusesTableSeeder.php
> +            'id' => 1,
[]の中身がまだインデントがずれているので直しましょう！

2020-12-01 12:22 UTC, yuto-ono commented on database/seeds/M_Sales_StatusesTableSeeder.php
> +            'id' => 1,
[]の中身がまだインデントがずれているので直しましょう！

2020-12-01 13:56 UTC, yuto-ono approved these changes

2020-12-01 13:56 UTC, yuto-ono commented
LGTM 👍

2020-12-01 13:56 UTC, merged