m_usersテーブルと5名分のテストデータを作成（taro)
quest-academia/yanbaru_ec_traning pull request #15
Opened 2020-11-25 09:55 UTC by TAROTH666

動作確認によりwelcome.blade.phpの変更があります。
また内容に関しまして、不備や疑問があればお伝えください！

2020-11-25 12:34 UTC, ryota100 commented on database/migrations/2020_11_25_170302_m_users.php
> +            $table->foreign('user_classification_id')->references('id')->on('m_users')->onDelete('cascade');
外部キー制約の記述に誤りがあるようですので、ご確認ください。
今回のプルリクで、user_classificationテーブルは作成しないのであれば、とりあえず記述削除でも大丈夫です。
よろしくお願いします。

2020-11-25 12:36 UTC, ryota100 commented
環境の構築など、お疲れ様です。

全体通して確認致しました。
一点指摘いたしましたので、よろしくお願い致します😊

2020-11-25 20:29 UTC, SekiYukihiro requested changes
お疲れ様でした！
確認しまして、
りょうたさんのご指摘の箇所を修正していただければOKかと思います:うふふ:
宜しくお願い致します。

2020-11-25 20:29 UTC, SekiYukihiro commented
お疲れ様でした！

確認しまして、
りょうたさんのご指摘の箇所を修正していただければOKかと思います:うふふ:
宜しくお願い致します。

2020-11-26 13:05 UTC, ryota100 commented on database/migrations/2020_11_25_170302_m_users.php
> +            $table->bigIncrements('user_id')->autoIncrement();
ここはidのままで大丈夫です。
PKはidとするのが一般的だからになります。

2020-11-26 13:08 UTC, ryota100 commented on database/migrations/2020_11_26_171847_m_users_classifications.php
> +            $table->bigIncrements('user_classification_id')->autoIncrement();
同様ですが、user_classification_idについてPKになりますのでidに変更お願いします。

2020-11-26 13:18 UTC, ryota100 commented on database/migrations/2020_11_25_170302_m_users.php
> +            $table->foreign('user_classification_id')->references('user_id')->on('m_users')->onDelete('cascade');
おそらくこんがらがっているかと思いますので、回答例としては以下になります。
 $table->foreign('user_classification_id')->references('id')->on('m_users_classifications')->onDelete('cascade');

これは、どういうことを言っているのかというと、
例であげたの()の3つ目から順に左に説明しますが、
m_users_classificationsテーブルの上にあるidとこのテーブルのuser_classification_idを関連づけるという記述をしています。
これにより、このusersテーブルで、m_users_classificationsテーブルの内容を参照できるようになります。

ここは、非常に理解しづらいところだと思っているので、頑張って理解できるようにしてみてください🤲

2020-11-26 13:25 UTC, ryota100 reviewed
テーブル追加お疲れ様です。
全体感として問題ないかと思います😊
外部キー制約に係る点について指摘したのと、こちらの都合でサンプルデータを改めて指示させていただきました。
以上、確認よろしくお願いします。

2020-11-26 13:25 UTC, ryota100 commented on database/seeds/M_UsersClassificationsTableSeeder.php
> +        ]);
こちらデータ入れていただいてありがとうございます。
参考のデータ見てみたら、
出品者、購入者、管理者となっておりましたので、お手数ですが、ひとまずこちらの値に変えていただけたらと思います。よろしくお願いします。

2020-11-26 15:07 UTC, SekiYukihiro requested changes
bigIncrementsのところをコメントにて追加しました！

りょうたさんのご指摘と踏まえて、ご確認頂ければと思います！

難しい部分もあると思いますが、不明点あればお聞きください✨
他の方の書き方を見るのも、参考になると思いますよ！

2020-11-26 15:07 UTC, SekiYukihiro commented on database/migrations/2020_11_26_171847_m_users_classifications.php
> +            $table->bigIncrements('user_classification_id')->autoIncrement();
こちらは、incrementsで良いと思います。
bigIncrementsは、ものすごい数を登録される時に使われるのですが
今回はそこまでの数を想定していないという前提でOKかなと思います✨

また、autoIncrement()を付けなくても、
incrementsとすれば自動でIDの数が増加していく形になりますので
なしでOKです！

2020-11-26 15:07 UTC, SekiYukihiro commented on database/migrations/2020_11_25_170302_m_users.php
> +            $table->bigIncrements('user_id')->autoIncrement();
こちらは、incrementsで良いと思います。
bigIncrementsは、ものすごい数を登録される時に使われるのですが
今回はそこまでの数を想定していないという前提でOKかなと思います✨

また、autoIncrement()を付けなくても、
incrementsとすれば自動でIDの数が増加していく形になりますので
なしでOKです！

2020-11-27 11:08 UTC, ryota100 reviewed
サンプルデータについて指摘致しました。僕が見たところ、他は大丈夫かと思います。よろしくお願いします🤲

2020-11-27 11:08 UTC, ryota100 commented on database/seeds/M_UsersClassificationsTableSeeder.php
> +        ]);
こちらサンプルデータが全て出品者になっておりますので、こちらについて修正お願いします

2020-11-28 09:04 UTC, ryota100 commented on database/seeds/M_UsersClassificationsTableSeeder.php
> +        ]);
すいません。修正内容がおかしいようです。
出品者、出品者、購入者、管理者、購入者というサンプルデータになってて、同じ種類のデータが入ってます。
出品者、購入者、管理者の3つでいいと思いますので、確認ください。

2020-11-28 09:07 UTC, ryota100 commented
お疲れ様です。
変更の破棄とpushありがとうございます。
ただ、サンプルデータについて再度確認ください。
よろしくお願いします。

2020-11-28 11:51 UTC, ryota100 commented
修正確認致しました。
色々な修正、お疲れ様でした。
以上、よろしくお願いします🤲

2020-11-29 10:08 UTC, SekiYukihiro commented
OKです！
マージしました！

2020-11-29 10:09 UTC, SekiYukihiro approved these changes
OKです！

コンフリクト解消お疲れ様でした❗️
問題ないのでマージしました。

宜しくお願い致します😃

2020-11-29 10:10 UTC, merged