add: DB構築後 Migrate&Seederファイルの作成と実行
quest-academia/yanbaru_ec_traning pull request #17
Opened 2020-11-26 23:01 UTC by makoto2222

お疲れ様です！

DB構築後、下記を行いました。

- マイグレーションの実行

- シーダーファイルの作成、実行

お手すきの際に、内容のご確認をお願いいたします。

2020-11-27 14:14 UTC, shimotaroo reviewed
レビューしました！
必要なところ（FK制約付与）がコメントアウトされてしまっていたので外しましょう！
他のところはよく書けているいますね😄

@yuto-ono 
レビューお願いします！！

2020-11-27 14:14 UTC, shimotaroo commented on database/migrations/2020_11_25_073058_create_t_orders_details_table.php
> +            //$table->foreign('product_id ')->references('id')->on('m_products')->onDelete('cascade');
FK必要ですのでコメントアウト外しましょう！

2020-11-27 14:14 UTC, shimotaroo commented on database/migrations/2020_11_26_074713_create_t_orders_table.php
> +            //$table->foreign('user_id')->references('id')->on('m_users')->onDelete('cascade');
ここもコメントアウト外しましょう！

2020-11-28 04:25 UTC, makoto2222 commented
> レビューしました！
> 必要なところ（FK制約付与）がコメントアウトされてしまっていたので外しましょう！
> 他のところはよく書けているいますね😄
> 
> @yuto-ono
> レビューお願いします！！

2020-11-28 04:26 UTC, makoto2222 commented on database/migrations/2020_11_25_073058_create_t_orders_details_table.php
> +            //$table->foreign('product_id ')->references('id')->on('m_products')->onDelete('cascade');
@ゆーたろーさん

FKのコメントアウト、外して、再度コミットしました！

2020-11-28 04:26 UTC, makoto2222 commented on database/migrations/2020_11_26_074713_create_t_orders_table.php
> +            //$table->foreign('user_id')->references('id')->on('m_users')->onDelete('cascade');
@ゆーたろーさん

FKのコメントアウトを外して、再度コミットしました！

2020-11-30 00:02 UTC, makoto2222 commented
PRを再オープンしました！

2020-11-30 11:38 UTC, shimotaroo reviewed
確認しました！
問題ないかと思います👍

@yuto-ono 
レビューお願いします！
問題なければマージお願いします😄

2020-11-30 11:39 UTC, shimotaroo approved these changes

2020-12-01 14:18 UTC, yuto-ono commented on database/migrations/2020_11_25_073058_create_t_orders_details_table.php
> +            $table->foreign('product_id ')->references('id')->on('m_products')->onDelete('cascade');
不要なスペースが入っているので消しましょう！
`'product_id '`

2020-12-01 14:25 UTC, yuto-ono commented
よくできています！
１点だけ修正があるのでご確認ください 🙏 
また、 database/seeds/DatabaseSeeder.php がコンフリクトしているので解消しましょう！

2020-12-01 22:09 UTC, yuto-ono requested changes
よくできています！
１点だけ修正があるのでご確認ください 🙏
また、 database/seeds/DatabaseSeeder.php がコンフリクトしているので解消しましょう！

2020-12-05 04:23 UTC, makoto2222 commented on database/migrations/2020_11_25_073058_create_t_orders_details_table.php
> +            $table->foreign('product_id ')->references('id')->on('m_products')->onDelete('cascade');
@yuto-onoさん
不要なスペース削除しました！

2020-12-05 04:48 UTC, makoto2222 commented
> よくできています！
> １点だけ修正があるのでご確認ください 🙏
> また、 database/seeds/DatabaseSeeder.php がコンフリクトしているので解消しましょう！

database/seeds/DatabaseSeeder.php のコンフリクトを解消しました！
ご確認のほどお願いいたします。

2020-12-05 06:48 UTC, yuto-ono commented
LGTM 👍

2020-12-05 06:48 UTC, yuto-ono approved these changes

2020-12-05 06:49 UTC, merged