新規ユーザ登録機能の実装
quest-academia/yanbaru_ec_traning pull request #24
Opened 2020-12-06 06:56 UTC by keisuke-1-7

・RegisterController.php
・マイグレーションファイル
に関して重点的に確認していただきたいです。
よろしくお願いいたします。

2020-12-06 07:05 UTC, keisuke-1-7 commented on app/Http/Controllers/Auth/RegisterController.php
>          ]);
createする要素はこの内容で大丈夫でしょうか？
新規ユーザがフォームで送る内容を要素として取り入れましたが、マイグレーションファイルに記載されている他の要素はなくてよろしいでしょうか？

2020-12-06 07:05 UTC, keisuke-1-7 commented on database/migrations/2020_11_25_170302_m_users.php
>          });
修飾子の付け方に関して重点的に評価いただきたいです。
delete_flagはnullable()で良いのか？など

2020-12-06 07:05 UTC, keisuke-1-7 commented on public/css/base.css
>      .wrapper {
全体のcssファイルを少し編集しましたが大丈夫でしょうか？
この記載がなければ長いページだとfooterが浮き上がってしまいます。。

2020-12-06 12:31 UTC, ryota100 commented on app/Http/Controllers/Auth/RegisterController.php
> +            'email' => ['string', 'email', 'max:255', 'unique:users'],
emailに'required'が抜けているかと思いますので、追加ください。

2020-12-06 13:34 UTC, ryota100 reviewed
作成お疲れ様です。
全体的に良いと思います😊
現状、フォーム入力のない、user_classification_idをdefaultで１にされて、
もう一つのdelete_flagについては、nullableで処理されたというのが、今回の問題点だったのかなと思います。
今後、論理削除など実装するときは、また変更するときは来るのかなという認識でいます。
ひとまず、私の方からは以上です。
よろしくお願いします。

2020-12-06 13:34 UTC, ryota100 commented on app/Http/Controllers/Auth/RegisterController.php
>          ]);
基本的に入れる必要があるかと思いますが、idなど規定値が最初から入る設定になっているものは必要ないです。
今回その他入れてないカラムで、user_classification_idについては、migrationファイルでdefaultを使って、1にしていますので、特に他に入れる必要はないかと思います。

2020-12-06 21:43 UTC, SekiYukihiro commented on resources/views/auth/register.blade.php
> +                                {!! Form::text('first_name', old('first_name'), ['class' => 'form-control-sm d-inline col-sm-5']) !!}
ログイン画面と、新規登録画面で
入力フォームの枠線の太さが違うので、統一して頂ければよりいいと思います😊

2020-12-06 22:28 UTC, SekiYukihiro requested changes
確認しました。
いろいろご配慮いただいているなと感じました。

いくつか修正いただきたい点を書きましたので、
ご確認頂ければと思います😊

宜しくお願い致します❗️

2020-12-06 22:28 UTC, SekiYukihiro commented on app/Http/Controllers/Auth/RegisterController.php
> +            'zipcode' => ['required', 'integer', 'digits:7'],
0から始まる郵便番号を入力した場合、
現状だとバリデーションエラーになってしまいます。

（設計書にintegerと記載されているのですが、integerではなく）
numeric という型に指定した方がいいかなと思いました😊

2020-12-06 22:28 UTC, SekiYukihiro commented on app/Http/Controllers/Auth/RegisterController.php
> +            'apartments' => ['required', 'string', 'max:20'],
ここのmaxの数は何を基準に決められていますでしょうか？

１５字や２０字だと厳しすぎる場合もあるかもしれないので
(マンション名などにアルファベットが入ってきた場合など)
データベースの最大入力値と統一してもいいかなと思いました。

2020-12-06 22:28 UTC, SekiYukihiro commented on app/Http/Controllers/Auth/RegisterController.php
> +            'phone_number' => ['required', 'string', 'max:15'],
こちらも、numeric の方がいいですかね。

2020-12-07 14:38 UTC, keisuke-1-7 commented on app/Http/Controllers/Auth/RegisterController.php
>          ]);
承知いたしました。
ご指摘と解説ありがとうございます！

2020-12-07 14:39 UTC, keisuke-1-7 commented on database/migrations/2020_11_25_170302_m_users.php
>          });
レビューありがとうございます。
default()を使っていこうと思います！

2020-12-07 14:40 UTC, keisuke-1-7 commented on public/css/base.css
>      .wrapper {
ありがとうございます！！

2020-12-07 14:42 UTC, keisuke-1-7 commented on resources/views/auth/register.blade.php
> +                                {!! Form::submit('登録', ['class' => 'btn btn-primary w-50']) !!}
失礼いたしました。
訂正しておきます！

2020-12-07 14:43 UTC, keisuke-1-7 commented on app/Http/Controllers/Auth/RegisterController.php
> +            'zipcode' => ['required', 'integer', 'digits:7'],
承知いたしました。
ご指摘ありがとうございます！
変更しておきます！

2020-12-07 14:46 UTC, keisuke-1-7 commented on app/Http/Controllers/Auth/RegisterController.php
> +            'apartments' => ['required', 'string', 'max:20'],
バリデーションに関しては全て画面定義所に記載されている項目で作成いたしましたが、
確かに厳しい制限ですので、変更しておきます！

2020-12-07 14:46 UTC, keisuke-1-7 commented on app/Http/Controllers/Auth/RegisterController.php
> +            'phone_number' => ['required', 'string', 'max:15'],
承知いたしました！
変更しておきます。

2020-12-08 13:13 UTC, ryota100 commented
お疲れ様です。
修正確認致しました。
よろしくお願いします。

2020-12-08 13:47 UTC, SekiYukihiro requested changes
確認しまして、OKです！

指摘した部分全て修正されて
素晴らしいと思います😊

引き続き、カート機能など難しいですが
頑張って実装していきましょう。

宜しくお願い致します✨

2020-12-08 13:48 UTC, SekiYukihiro approved these changes
確認しまして、OKです！

指摘した部分全て修正されて
素晴らしいと思います😊

引き続き、カート機能など難しいですが
頑張って実装していきましょう。

宜しくお願い致します✨

2020-12-08 13:48 UTC, merged