Feature/juri/front user register　ユーザ登録画面（じゅり）
quest-academia/yanbaru_ec_traning pull request #31
Opened 2020-12-10 19:11 UTC by Juri-O

お世話になっております。
ユーザ登録画面を作成しましたので、ご確認をよろしくお願いいたします。

2020-12-10 23:15 UTC, shimotaroo approved these changes
レビューしました！！
一応承認はしておりますが、ゆーとさんのレビューを待ちましょう！！

2020-12-10 23:15 UTC, shimotaroo commented on app/Http/Controllers/Auth/RegisterController.php
> +                'phone_number' => ['required','string','numeric', 'digits_between:1,15'],
ここインデントがズレているので修正しましょう！

2020-12-10 23:15 UTC, shimotaroo commented on app/Http/Controllers/Auth/RegisterController.php
>      }
バリデーションの方法も問題ないと思います！
シンプルにすごいです👍

なお、公式ドキュメント（https://readouble.com/laravel/5.8/ja/validation.html）を見ると


$messages = [
    'required' => 'The :attribute field is required.',
];

$validator = Validator::make($input, $rules, $messages);

こんな感じで書かれているので、
上記のようにルールとメッセージを別の変数に格納して書いてあげるとより見やすくなるかもしれませんね！
（僕的にはどちらでも良いかなと思うのでゆーとさんに決めていただきましょうw）

2020-12-10 23:15 UTC, shimotaroo commented on routes/web.php
> +Route::post('signup','Auth\RegisterController@register')->name('signup.post');
認証系のルーティングはAuth::routes();と書くだけで一通り準備してもらえるのでこれ使っても良いかもしれません！！
https://qiita.com/sola-msr/items/c966b30bce888ce77546

ゆーとさん、判断お願いします👍

2020-12-10 23:15 UTC, shimotaroo commented on resources/views/auth/register.blade.php
> +                    {!! Form::text('last_name', old('last_name'),['class' => 'form-control  ml-1 col-lg-5']) !!}
すごいどうでも良いんですけど、ここ2文字分開いてましたw

form-control  ml-1

2020-12-10 23:15 UTC, shimotaroo commented on resources/views/auth/register.blade.php
> +@endsection
全体的に良く書けているのではないでしょうか！！
当時の僕より遥かにすごいです😄

2020-12-11 01:59 UTC, shimotaroo commented on routes/web.php
> +Route::post('signup','Auth\RegisterController@register')->name('signup.post');
↑これシカトしてください！
今のルーティングで問題ありません！

2020-12-12 04:41 UTC, yuto-ono commented on resources/views/auth/register.blade.php
> +@endsection
これはすごいです！　よくできています！

2020-12-12 04:44 UTC, yuto-ono requested changes
基本的によくできていてすばらしいです！
ゆーたろーさんが指摘したインデントとスペース1個多いのだけ直しましょう！

2020-12-12 04:44 UTC, yuto-ono commented on app/Http/Controllers/Auth/RegisterController.php
>      }
問題ありません！

2020-12-12 08:22 UTC, Juri-O commented on app/Http/Controllers/Auth/RegisterController.php
> +                'phone_number' => ['required','string','numeric', 'digits_between:1,15'],
盛大にずれてるのに気づいてませんでした！修正します！

2020-12-12 08:24 UTC, Juri-O commented on app/Http/Controllers/Auth/RegisterController.php
>      }
問題ないとのお返事をいただけたので、ひとまずこのままにさせていただきます。
ずらっと大量に並んでるのはちょっとどうかなとは思っていたので、個人的に変数を使った書き方も試してみますね。

2020-12-12 08:29 UTC, Juri-O commented on resources/views/auth/register.blade.php
> +                    {!! Form::text('last_name', old('last_name'),['class' => 'form-control  ml-1 col-lg-5']) !!}
２文字スペース、たぶんコピペしたときにスペース余分に開けちゃってたんですね。消しておきます！

2020-12-12 08:33 UTC, Juri-O commented
お二人ともご確認ありがとうございました！
ご指摘のあったインデントのずれを揃えて、スペースを１マスに修正しました。
ご確認をよろしくお願いいたします。

2020-12-12 09:12 UTC, shimotaroo commented
問題なしです！！！

2020-12-15 06:38 UTC, yuto-ono approved these changes
完璧です！ LGTM 👍

2020-12-15 06:38 UTC, merged