Feature/tetsuyoshi/create user info edit
quest-academia/yanbaru_ec_traning pull request #33
Opened 2020-12-17 14:23 UTC by yoshitaro-yoyo

・ユーザー情報表示（show）
・ユーザー情報修正（edit/update）
・ユーザー情報削除（destoroy）

上記の各機能実装の他、

・header（ログイン後）にユーザー情報表示画面へのルーティングの記述
・ユーザー情報修正画面のLaravelCollective化
・web.phpのルーティングをRESTfulに変更
・web.phpのクロージャなルーティングを削除

2020-12-18 13:41 UTC, shimotaroo reviewed
お疲れ様です！

バックエンドの処理自体はしっかり書けていて非常に良いと思います！

タスク量が増えて大変だとは思いますが、コーディングでのケアレスミスが目立つので焦らずやっていきましょう！

インデントとかはちゃんと意識した方が良いです👍

2020-12-18 13:41 UTC, shimotaroo commented on resources/views/users/edit.blade.php
> +						<button class="btn btn-primary mr-5 ml-5"type="submit">　　修　正　　</button>
">　　修　正　　</button>

修正の文字の開きが気になります！
GitHubのページでこう見えてるだけならOKです👍
「退会」も同様

2020-12-18 13:41 UTC, shimotaroo commented on routes/web.php
> +});*/
不要なコードは削除しましょう！！

2020-12-18 13:41 UTC, shimotaroo commented on app/Http/Controllers/UserController.php
> +use App\User;//Modelの読み込みを宣言する
ここのコメントはクラスを使えるようにしているだけなので不要かと思います！

2020-12-18 13:41 UTC, shimotaroo commented on app/Http/Controllers/UserController.php
> +		return view('front.before_login');
ここインデントの幅広いように見えますが、合ってますか！？
（このファイル全てです）

※見間違えだったらすみませんm(__)m

2020-12-18 13:41 UTC, shimotaroo commented on app/Http/Controllers/UserController.php
> +		//変数userにUserモデルを用いてテーブルデータを呼び出す
ここはコメントの内容が間違っています！！

正しくは「idが$idの値と同じUserモデルのインスタンスを取得して$userに格納」です！

難しい内容ですが、「変数userにデータを呼び出す」という言い回しは違うので上記参考にしてください👍

2020-12-18 13:41 UTC, shimotaroo commented on resources/views/front/before_login.blade.php
> +                		お持ちでない方はこちら
インデントあけましょう！

2020-12-18 13:41 UTC, shimotaroo commented on resources/views/front/before_login.blade.php
> +                		お持ちの方はこちら
インデントあけましょう！

2020-12-18 13:41 UTC, shimotaroo commented on resources/views/users/edit.blade.php
> +				{{ method_field('PUT') }}
{{ method_field('PUT') }}のインデントが開き過ぎに見えます！

2020-12-18 13:41 UTC, shimotaroo commented on resources/views/users/edit.blade.php
> +        </div>
インデント見直しましょう！

2020-12-18 13:59 UTC, yoshitaro-yoyo commented on app/Http/Controllers/UserController.php
> +use App\User;//Modelの読み込みを宣言する
承知いたしました！

2020-12-18 14:00 UTC, yoshitaro-yoyo commented on app/Http/Controllers/UserController.php
> +		//変数userにUserモデルを用いてテーブルデータを呼び出す
ご指摘ありがとうございます！
勉強になります！ありがとうございます

2020-12-18 14:02 UTC, yoshitaro-yoyo commented on resources/views/users/edit.blade.php
> +				{{ method_field('PUT') }}
すみません。インデント関連はフォーマット拡張機能の不具合みたいです

2020-12-18 14:04 UTC, yoshitaro-yoyo commented on resources/views/users/edit.blade.php
> +						{!! Form::label('first_name', '　　　姓', ['class' => 'd-inline']) !!}
レイアウトの崩れを強引に調整したものです。
全角スペースで強引に位置を合わせています。
下記の　
">　　修　正
も同様です。

レイアウト崩れで4日ほど時間かかってしまいまして…。
タスクが落ち着いたら修正したいと考えています。

2020-12-18 14:04 UTC, yoshitaro-yoyo commented on routes/web.php
> +});*/
こちらはログイン機能が実装されたら開放しようと思っています。
ミドルウエアでログイン認証が済んでいるユーザーのみにこのルーティングが適用されるようにしたいと思っています。
削除したほうがいいですか？

2020-12-18 21:55 UTC, shimotaroo approved these changes
僕からはOKです👍
お疲れ様でした！

あと細かいのですが、コメントはコードの上に書くのが一般的だと思いますので上に書きましょう〜！
https://www.php.net/manual/ja/language.basic-syntax.comments.php

2020-12-18 21:55 UTC, shimotaroo commented on routes/web.php
> +});*/
失礼しました😅であればOKです！
が、レビューされることも考えると必要なコメントアウトにはその理由を書くのが望ましいです！

2020-12-20 01:15 UTC, yuto-ono commented on resources/views/front/before_login.blade.php
> +              	</div>
この辺、おそらくtabとスペースが混ざっています。スペース4つに統一しましょう！

2020-12-20 01:28 UTC, yuto-ono requested changes
インデントにタブが混じっているようです。
見た目的に非常にわかりにくいので、気をつけましょう！

2020-12-20 01:28 UTC, yuto-ono commented on app/Http/Controllers/UserController.php
> +		return view('front.before_login');
おそらくインデントがタブになっていますね。規約通りスペース4つに直しましょう！

2020-12-20 01:28 UTC, yuto-ono commented on resources/views/users/show.blade.php
> +            <a class="btn btn-primary" {!! link_to_route('users.edit', '修正/退会する', ['user' => $user], []) !!}</a>
37行目、ちょっと書き方がおかしいです。
`<a class="btn btn-primary" href="{{ route('users.edit', ['user' => $user]) }}">修正/退会する</a>`
としましょう。

2020-12-22 11:39 UTC, yuto-ono requested changes
今のままだと自分以外のユーザー情報を閲覧したり編集したりできるので修正しましょう！

2020-12-22 11:39 UTC, yuto-ono commented on app/Http/Controllers/UserController.php
> +    }
この実装だと自分以外のユーザー情報も閲覧できてしまいませんか？
ログインしているユーザー以外の情報を閲覧できないように実装しましょう。

2020-12-22 11:39 UTC, yuto-ono commented on app/Http/Controllers/UserController.php
> +    }
この実装だと自分以外のユーザー情報も編集できてしまいませんか？
ログインしているユーザー以外の情報を編集できないように実装しましょう。

2020-12-22 11:39 UTC, yuto-ono commented on app/Http/Controllers/UserController.php
> +    }
この実装だと自分以外のユーザー情報も編集できてしまいませんか？
ログインしているユーザー以外の情報を編集できないように実装しましょう。

2020-12-22 11:39 UTC, yuto-ono commented on app/Http/Controllers/UserController.php
> +    }
この実装だと自分以外のユーザー情報も削除できてしまいませんか？
ログインしているユーザー以外の情報を削除できないように実装しましょう。

2020-12-28 14:58 UTC, shimotaroo reviewed
レビューしました！
ゆーとさんの意見もお聞きしたいです！

2020-12-28 14:58 UTC, shimotaroo commented on resources/views/front/before_login.blade.php
> +                </div>
ここインデントに余計なものが入っているように見えますのでご確認お願いします！

2020-12-28 14:58 UTC, shimotaroo commented on app/Http/Controllers/UserController.php
> +    }
@yoshitaro-yoyo @yuto-ono 
色々試行錯誤して素晴らしい実装だと思います🥰

ちょっと思ったんですが、これじゃダメなんですかね？？

```
if (Auth::id() === $id）{
    //
} else {
    //
}
``` 
```

2020-12-29 23:43 UTC, yuto-ono approved these changes
OKです！
難しいところですが、よくできました！

2020-12-29 23:43 UTC, yuto-ono commented on app/Http/Controllers/UserController.php
> +    }
OKです！　すばらしいです！
もちろんゆーたろーさんが提案された方法でも大丈夫です！

2020-12-29 23:44 UTC, merged