add:ログイン機能実装（まこと）
quest-academia/yanbaru_ec_traning pull request #34
Opened 2020-12-17 22:45 UTC by makoto2222

お疲れ様です！

ログイン機能を実装しましたのでご確認お願いいたします。

【実装したこと】

- php artisan make:auth のコマンド実行
- バリデーションの入力 => resources/lang/jp
- login.blade.phpの作成
- home.blade.phpの作成

よろしくお願いいたします。

2020-12-18 13:54 UTC, shimotaroo reviewed
お疲れ様でした！

処理はしっかり書けていると思います😄

インデントのズレがあるので意識しながらコーディングしていきましょう〜！

2020-12-18 13:54 UTC, shimotaroo commented on resources/lang/jp/validation.php
> +    //修正後
不要なコード・コメントアウトは消しましょう！

2020-12-18 13:54 UTC, shimotaroo commented on resources/lang/jp/validation.php
> +        ],
インデントを合わせましょう！

2020-12-18 13:54 UTC, shimotaroo commented on resources/views/auth/login.blade.php
> +                        <div>
この２つのインデントは同じ位置にしましょう！！
（labelタグの中にdivタグがあるわけではないので）

2020-12-18 13:54 UTC, shimotaroo commented on resources/views/auth/login.blade.php
> +                        <div>
上記同様です👍

2020-12-18 13:54 UTC, shimotaroo commented on resources/views/auth/login.blade.php
> +                            <input id="email" type="email" class="@error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required ="email" autofocus>
FormはLaravel Collective使えませんか？

2020-12-18 13:54 UTC, shimotaroo commented on resources/views/auth/login.blade.php
> +                            <input id="password" type="password" class="@error('password') is-invalid @enderror" name="password" required ="current-password">
ここもLaravel Collectiveでできませんか？

2020-12-18 13:54 UTC, shimotaroo commented on resources/views/commons/header.blade.php
> +        @endif
インデント合わせましょう😄

2020-12-22 13:08 UTC, yuto-ono requested changes
インデント等、直しましょう！

2020-12-22 14:21 UTC, shimotaroo approved these changes
OKです！
お疲れ様でした！
！

2020-12-22 14:25 UTC, yuto-ono approved these changes
OKです！

2020-12-22 14:25 UTC, merged