Feature/taro/create users table
quest-academia/yanbaru_ec_traning pull request #37
Opened 2020-12-20 05:38 UTC by TAROTH666

検索機能の作成が完了致しました。
初期状態では入力フォームのみを表示し、検索することで結果テーブルを表示する仕様になります。
ご確認よろしくお願いいたします。

2020-12-20 10:21 UTC, ryota100 commented
お疲れ様です。
コード及びプラウザでの動き確認しました。
自力でここまで処理書けるのは、本当に素晴らしいと思います。


処理の複雑な文(今回で言うとProductController)について、コメント文を処理のごとに記述するとよりいいかと思います。
共同開発者に何をしているのか分かるようにするためと自身も言語化することで理解の向上にも繋がるためです。

是非やってみてください。

2020-12-20 20:35 UTC, quest-academia requested changes
以前よりもとてもスマートな記述になりましたね❗️
とても良い感じです！

１点だけ、修正頂きたい点があります！

現状だと、少し問題がありまして
「¥」「%」「_」などの記号をふくむ検索キーワードで検索を掛けると、おそらく全件検索できてしまうと思います。

これを解消するために、これらの文字列が検索キーワードの中に含まれていた場合、
これらの文字列をエスケープする処理をsearchメソッドの中に書きましょう！

あと少しの修正ですので、是非とも頑張ってみてください😊

2020-12-20 20:35 UTC, quest-academia commented on app/MCategory.php
> +    }
モデルに、役割を分離させていて、とても良いですね😊

2020-12-20 20:35 UTC, quest-academia commented on app/Http/Controllers/ProductController.php
> +        $products = $query->orderBy('category_id', 'asc')->paginate(15);
この辺、以前よりもとてもスマートな記述になりましたね❗️
とても良い感じです！

１点だけ、修正頂きたい点があります！

現状だと、少し問題がありまして
「¥」「%」「_」などの記号で検索を掛けると、おそらく全件検索できてしまうと思います。

これを解消するために、これらの文字列が検索キーワードの中に含まれていた場合、
これらの文字列をエスケープする処理をsearchメソッドの中に書きましょう！

あと少しの修正ですので、是非とも頑張ってみてください😊

2020-12-22 20:46 UTC, SekiYukihiro approved these changes
あと、今回は要件定義として指定されていないのでOKなのですが、
２単語以上の検索にも耐えうるような実装も今後学んでいっていただけると
とても良いと思います.

お疲れ様でした!

2020-12-22 20:46 UTC, SekiYukihiro commented on app/Http/Controllers/ProductController.php
> +        return str_replace(['\\', '%', '_'], ['\\\\', '\%', '\_'], $str);
OKです！

欲を言えば、
ゆーやさんのアドバイスと全く同じコードになってしまったのが少し残念ですが
今後、str_replaceなどの関数を自分で調べて実装できる実力を付けていきましょう😊

2020-12-22 20:48 UTC, quest-academia approved these changes

2020-12-22 20:48 UTC, merged