商品詳細画面の実装（けーすけ）
quest-academia/yanbaru_ec_traning pull request #38
Opened 2020-12-21 12:03 UTC by keisuke-1-7

画面上の挙動はSlackにてご確認いただいた通りですが、
データ（変数）の受け渡しや、セッションの使用方法があっているかが少々不安があります。
コードレビューの程よろしくお願いいたします。

2020-12-21 12:06 UTC, keisuke-1-7 commented on app/Http/Controllers/ProductController.php
> +    {
以下がセッションに保存している部分です。

2020-12-21 12:07 UTC, keisuke-1-7 commented on app/Http/Controllers/ProductController.php
> +    {
以下がセッションからデータを取得している部分です

2020-12-21 12:08 UTC, keisuke-1-7 commented on app/Product.php
> +
申し訳ありません、以下を削除し忘れておりました。
訂正時に削除しておきます。

2020-12-21 14:34 UTC, ryota100 commented
確認致しました。
まず、メキメキ力を伸ばしており、素晴らしいと思います。
sessionを使ったデータの保存と取得もしっかりできていると思います。

１点、難しいところではあるのですが、2回目にカートに入れると、1回目のカート情報が上書きされてしまい、１点しかカート情報が受け取れない状態ですので、修正が必要そうです。

保存するsession情報を配列にして、複数の商品情報を保存できるようにしましょう。2回目以降に来たものも保存できるような処置が必要になります。難しいですが、少し試してみてください。

2020-12-23 15:31 UTC, keisuke-1-7 commented on app/Http/Controllers/CartController.php
> +
indexアクションの、ここより以下のコードがまだ上手く実装できておりませんので、ここまでの挙動をご確認いただければと思います。

43行目のdd($SessionData);にて個数選択し”カートへ”ボタンを押す毎に、配列型式でデータが増えていくことを確認しております。

2020-12-24 14:37 UTC, ryota100 commented
確認しました。

先日指摘した点について、うまく配列型式でデータの保存をされていて、素晴らしいと思います。
修正点について指摘はありません。
よろしくお願いします。

2020-12-24 20:46 UTC, quest-academia commented on app/Http/Controllers/CartController.php
> +
ここの空行は不要かと思います！

2020-12-24 21:06 UTC, quest-academia requested changes
確認しました！

難しいセッションをよくここまで考えられたと思います😊

いくつか直して欲しい部分を記述しましたので、ご確認いただければと思います😊
宜しくお願い致します！

2020-12-25 12:48 UTC, keisuke-1-7 commented on resources/views/iteminfo.blade.php
> +                                {{ Form::hidden('ProductId', $ProductInfo->id) }}
キャメルケースを勘違いしておりました、、
承知いたしました、訂正しておきます！

2020-12-25 12:49 UTC, keisuke-1-7 commented on app/Http/Controllers/CartController.php
> +        dd($SessionData);
承知いたしました！
変更いたします！

2020-12-25 12:49 UTC, keisuke-1-7 commented on app/Http/Controllers/CartController.php
> +
承知いたしました！

2020-12-25 12:57 UTC, keisuke-1-7 commented on app/Http/Controllers/CartController.php
> +
承知いたしました！
コメントを記載しておきます！

2020-12-25 20:41 UTC, quest-academia approved these changes
OKです！

問題ないと思いますので、マージしますね。

難しい実装、おつかれさまでした✨

2020-12-25 20:42 UTC, merged