Feature/katomakoto/make order functions（カトウマコト)
quest-academia/yanbaru_ec_traning pull request #40
Opened 2020-12-31 05:06 UTC by Torippana

ご確認よろしくお願いします

2021-01-01 11:48 UTC, ryota100 commented on app/Http/Controllers/OrderController.php
> +            // $deleteResult = true;
110行のコメントアウト不要であれば削除。

2021-01-01 12:26 UTC, ryota100 commented
実装お疲れ様です。

正直本当にレベルが高いと思っていて、めちゃくちゃすごいと思います。
自分で処理を組み立てて、やれているのもすごいです。

確認した中で、プラウザでみた際に2点気になったことがあったので、指摘いたします。
１点目に、直近3ヶ月の注文を表示を押した時に、1/1の注文日時の注文が表示されなかったことです。
２点目に、注文履歴画面のページネーションについて3ページ目が表示されず、存在する3ページ以降に遷移できなかったことです。

以上、よろしくお願いします。

2021-01-01 13:34 UTC, ryota100 commented
直近3ヶ月の注文を表示を押した際の修正確認しました。
OKです。
よろしくお願いします。

2021-01-01 23:43 UTC, quest-academia requested changes
細部までよく考えられていて、とてつもなく素晴らしいと思います😊

ほぼ問題ないのですが、あえて書き直すなら・・・
という点をいくつか書きましたので、
修正&修正しなくても今後の参考にしていただければと思います❗️

何卒、宜しくお願い致します！

2021-01-01 23:43 UTC, quest-academia commented on app/Http/Controllers/OrderController.php
> +            ]
やんばるコードレビュー基準のPDFデータに、
Controller →Viewへの変数の渡し方についての記述があります。

return view(‘admin.profile’, $data);

このような、一旦$dataに格納してからview()に渡すという書き方が
今回のプロジェクトにおいては推奨されますので、
今の書き方でも全く悪くはないのですが、
書き換えましょう！

他のviewに渡す部分も同様です😊

2021-01-01 23:43 UTC, quest-academia commented on app/Http/Controllers/OrderController.php
> +    }
こちらの記述でも全く問題ないのですが、
他の書き方として、

　TOrder::getBaseOrder()

のように、動的メソッドを使えば、
このコンストラクタは省略できますね！

2021-01-01 23:43 UTC, quest-academia commented on app/TOrder.php
> +            ->toSql();
よく考えられていて、素晴らしいと思います😊

今回はこの書き方で問題ないです。

ただ、joinでordersテーブルとorders_detailsテーブルを結合されているのですが
orderモデルとorders_detailモデルどうしを、１対１（ですかね？）の関係で結び付ければ、

コントローラでorderの情報だけをviewに渡して
viewにてorder_detailの情報を展開して表示することができ、
よりスマートな書き方が実現できるかと思います。

今後の参考にしてみてください✨

2021-01-02 01:22 UTC, Torippana commented on app/Http/Controllers/OrderController.php
> +        $user = Auth::user();
これはその通りですね！修正します

2021-01-02 01:30 UTC, Torippana commented on app/TOrder.php
> +            ->toSql();
これが一番聞きたかった箇所になるので、ご意見ありがとうございます。
以下の理由で今の書き方にしたのですが、

・注文データだけではなく、ユーザーデータ、発送状況ステータス、商品情報と
必要な物が多かったので一度で取得しちゃおう
確かにorderとorder_detailを一対一で結びつけてデータを取得する形ですました方がすっきりかけますね

2021-01-02 01:41 UTC, Torippana commented on app/TOrder.php
> +            ->toSql();
ここの部分が一番聞きたかった箇所になるので、レビューありがとうございます。
確かにorderとorder_detailをlaravelならではの一対一で結びつけてデータを取得する形ですました方がすっきりかけますね。
その場合は別で注文詳細画面の描画に必要なユーザー情報、発送状況ステータス、商品情報は各テーブルから取得し、PHP側で結合していくようにするということでしょうか。
コントローラー側の記述が多くなると思ってクエリで一度で取得しちゃおうとモリモリにしてしまったので、ここの部分はどうしたらいいものか是非知りたい箇所です

2021-01-02 11:56 UTC, SekiYukihiro commented on app/TOrder.php
> +            ->toSql();
修正箇所、OKです🙆‍♂️
確認致しました😊

データ取り出しに関しては、こちらを参考にしてみてください！
（これが完全な正解ではないのですが、参考までに作ってもらったものです）

https://github.com/mushajobs/YambaruECSite/blob/develop/app/Http/Controllers/FrontOrdersController.php

Orderテーブル以外のテーブルのデータも、特に結合させることなくそのままviewに持ってきて
View で表示させるときに工夫させて表示させる形ですね。


Viewは少し複雑になるのですが、
それほどモリモリ感もないかなと思います。

僕が前いたLaravel実務の現場でも、DBで結合させるというよりは、
この様な書き方が主流でしたので参考にして下さい😊

2021-01-02 11:59 UTC, SekiYukihiro approved these changes
修正OKです！

取り出し部分のコメントが
参考になれば幸いです😊

今の書き方、アドバイスした書き方、
両方のやり方を学んでいただけるととても良いと思います‼️

マージしますね！

2021-01-02 12:02 UTC, quest-academia approved these changes

2021-01-02 12:02 UTC, merged