add:ユーザ情報一覧表示、ユーザ情報編集・削除機能の実装（②）（たくみ）
quest-academia/yanbaru_ec_traning pull request #41
Opened 2021-01-03 06:40 UTC by takumi-isd

お疲れ様です。
ユーザ情報一覧表示、ユーザ情報編集・削除機能の実装が完成しましたのでご確認よろしくお願い致します。
遅くなってしまい申し訳ありません。

2021-01-03 14:48 UTC, ryota100 reviewed
実装お疲れ様です。
プラウザにて動きを確認しました。

動きについて概ね問題なくできておりますが、いくつか指摘事項が見つかりましたので、よろしくお願いします。

①ヘッダーについて
 <<<<HEADなどの文字が入っている。
ヘッダーの高さがかなり高くなり、画面定義書とズレが生じていますので、画面定義書と同じような表示になるように修正してください。

②複数あるcontrollerについて
UserDeleteController.php
UserEditController.php
UserInfoController.php
の3つのコントローラーにある処理を
UserControllerの一つにまとめましょう。
Userに関わる処理を複数のcontrollerに書くのは、一般的ではなく、処理も追いづらいため。

③validation処理の追加について
ユーザー情報編集(更新)に関わる処理についてvalidation処理を加えましょう。
laravelQuesteを見ながら作ってみてください。
validationの詳細については、画面定義書をご覧ください。
（名前などを空にして変更しようとするとエラー画面が表示されてしまうため）

2021-01-03 14:48 UTC, ryota100 commented on resources/views/commons/header.blade.php
> +<<<<<<< HEAD
誤字かと思います。以下修正願います。

2021-01-03 14:48 UTC, ryota100 commented on resources/views/commons/header.blade.php
> +=======
誤字かと思います。以下修正願います。

2021-01-03 14:48 UTC, ryota100 commented on resources/views/commons/header.blade.php
> +>>>>>>> develop_alpha
誤字かと思います。以下修正願います。

2021-01-05 15:26 UTC, ryota100 commented
修正対応お疲れ様です。

指摘していた、ヘッダーの誤り、controllerをまとめること、validationの追加について、確認いたしました。

(今後時間があればvalidaiton表示を日本語化するのに挑戦してみてもいいかもしれません。)
僕からは以上です。よろしくお願いします。

2021-01-05 21:20 UTC, quest-academia requested changes
確認しました！
がんばって、ご自分で考えながら作られていて素晴らしいと思います:ピカピカ:お疲れ様でした。
フォームリクエストの利用など、いくつかコメントしましたので、
ご確認願います:ぽっ:

2021-01-05 21:20 UTC, quest-academia commented on resources/views/auth/user_delete.blade.php
> +</main>
たくみさんの作っていただいた仕様だと
　退会ボタンを押す　→　退会確認ページへ移動　→　はい　→　退会処理実行
となっており、

設計書の仕様ですと
　退会ボタンを押す　→　即、退会処理実行
となっています。

実装上はたくみさんの仕様が使いやすく良いとは思うのですが、
原則設計書にしたがって作成するのが基本ではあります。

今の仕様はどなたかのアドバイスや、何かの記事を参考にされたのでしょうか？

2021-01-05 21:20 UTC, quest-academia commented on app/Http/Controllers/UserController.php
> +        // ここまでvalidation処理について追加
しっかりバリデーションができていると思います😊

今のままでもOKなのですが、
少し発展的な内容で
この部分のバリデーションを、丸々別ファイルとして切り分けることで
コードの可読性を上げる方法があります。

LaravelQuestでも利用していませんでしたが、
可能であれば、下記の記事を参考に、フォームリクエストという技術を使って、
この部分を切り出してみましょう✨

・フォームリクエストについて
https://qiita.com/sakuraya/items/abca057a424fa9b5a187

2021-01-08 14:57 UTC, ryota100 commented
実装お疲れ様です。
フォームリクエスト の実装、会得されてとてもいいですね。
プラウザ上、コード上にて問題なしです。
よろしくお願いします。

2021-01-08 23:14 UTC, SekiYukihiro approved these changes
お疲れ様でした！

フォームリクエストを利用することで、
バリデーションの記述がとてもすっきりしましたね😊

今後、是非積極的にフォームリクエストを利用してみてください✨

他の修正も問題ありませんでしたので、
マージさせて頂きました。

引き続き頑張りましょう、宜しくお願い致します✨

2021-01-08 23:14 UTC, SekiYukihiro commented on app/Http/Controllers/UserController.php
> +    {
これでこの部分がとてもすっきりしたと思います😊
とても良いですね！

2021-01-08 23:16 UTC, quest-academia approved these changes

2021-01-08 23:16 UTC, merged