t_purchase_tableのマイグレーション作成（gyagariko31）
quest-academia/yanbaru_ec_traning pull request #45
Opened 2021-01-10 05:30 UTC by gyagariko31

外部キーのところはコメントアウトしています

2021-01-11 06:23 UTC, shimotaroo requested changes
レビューしましたので回答および修正お願いします！

2021-01-11 06:23 UTC, shimotaroo commented on resources/views/welcome.blade.php
> +                    o
ここの修正は不要なので戻しておいてください！！

2021-01-11 06:23 UTC, shimotaroo commented on database/migrations/2021_01_10_025346_create_t_purchases_table.php
> +            $table->timestamp('purchase_date')->nullable();
確認したいのですが、purchase_dateカラムだけNULL許容している理由はありますか？

2021-01-11 06:23 UTC, shimotaroo commented on database/migrations/2021_01_10_025346_create_t_purchases_table.php
> +            // $table->integer('product_id');
カラムを追加するところはコメントアウト不要です！
（コメントアウトは外部キー制約をつけるところだけでOKです）

2021-01-11 21:18 UTC, gyagariko31 commented on database/migrations/2021_01_10_025346_create_t_purchases_table.php
> +            $table->timestamp('purchase_date')->nullable();
# @shimotaroo

2021-01-13 21:29 UTC, closed without merging

2021-01-13 21:35 UTC, gyagariko31 reviewed
修正しました