[add] 注文関連テーブル migrationfile作成 first commit
quest-academia/yanbaru_ec_traning pull request #47
Opened 2021-01-10 16:54 UTC by tomo-rrow86

担当箇所：注文関連テーブル
 （t_orders、t_orders_details、m_shipments_statuses）

※ m_users , m_products テーブルとの外部キー制約は、それぞれのテーブルがまだないのでコメントアウトにしています。

2021-01-11 15:26 UTC, ryota100 reviewed
お疲れ様です。

実装について問題ありません。
seederのところだけ、こちらの都合ではあるのですが、指摘させていただきましたので、そちらだけ修正ください。
よろしくお願いします。

2021-01-11 15:26 UTC, ryota100 commented on database/seeds/M_Shipment_StatusesTableSeeder.php
> +            ],
お手数おかけますが、ここのseederデータについては、
未発送、
発送済
入荷待ち
の3データに入れ替えていただけると有り難いです。
よろしくお願いします。

2021-01-12 11:55 UTC, ryota100 commented
確認いたしました。
ありがとうございます。
問題ありません。
よろしくお願いします。

2021-01-12 14:27 UTC, shimotaroo requested changes

2021-01-12 14:27 UTC, shimotaroo commented on database/seeds/DatabaseSeeder.php
> +            //UsersTableSeeder::class,
ここはmiyaさんのプルリクで追記されるのでコメントアウトごと削除しましょう！
（原則プルリクには不要はコメントアウトは消しておきましょう）

2021-01-12 14:27 UTC, shimotaroo commented on database/seeds/M_Shipment_StatusesTableSeeder.php
> +            ],
Seederファイル共通なのですが、連想配列の場合こう書くのが一般的です！
（他2ファイルも同じです）

```
            [
                'shipment_status_name' => '未発送',
            ],
            [
                'shipment_status_name' => '発送済',
            ],
            [
                'shipment_status_name' => '入荷待ち',
            ],

2021-01-12 22:57 UTC, shimotaroo requested changes
シーダーファイルのインデントがズレてないので僕のコメント通りにしてください！

2021-01-14 10:16 UTC, tomo-rrow86 commented
インデントを修正いたしました。
失礼いたしました！

2021-01-14 10:23 UTC, shimotaroo approved these changes
バッチリです👌
お疲れ様でした！！
mergeします！

2021-01-14 10:23 UTC, merged