Feature/tera/create productstable(tera)
quest-academia/yanbaru_ec_traning pull request #48
Opened 2021-01-11 07:24 UTC by hirotera

確認よろしくおねがいします｡

2021-01-11 15:14 UTC, ryota100 reviewed
実装お疲れ様です。

概ね問題なくできているかと思います。
数点指摘させていただきましたので、ご確認及び修正お願いします。

$table->timestamps('');については、
productテーブルについてregist_dateカラムがあるので必要ないかと思います。
categoryテーブルとsale_statusについては、あっても問題ないかなとも思うのですが、基本作成、更新されないテーブルなのでこちらもなしでいいと考えてます。
以上、よろしくお願いします。

2021-01-11 15:14 UTC, ryota100 commented on database/migrations/2021_01_11_110329_create_m_products_table.php
> +            $table->timestamps('');
①カラムを作成するまとまりの下に
外部キー制約を作るコードとカラムを作るコードのまとまりを分けて書いた方がコード管理がしやすくなるかと思いますので、外部キー制約のコードは、下にまとめて書くと分かりやすいです。

②priceカラムが抜けてましたので修正願います。

③外部キー制約について->onDelete('cascade')が抜けてましたので追加願います。

2021-01-11 23:22 UTC, hirotera commented on database/migrations/2021_01_11_110329_create_m_products_table.php
> +            $table->timestamps('');
確認ありがとうございます｡
指摘箇所修正しました｡
確認よろしくお願い致します｡

2021-01-11 23:51 UTC, ryota100 commented
お疲れ様です。

修正点問題なしです。
よろしくお願いします。

2021-01-12 13:52 UTC, shimotaroo requested changes

2021-01-12 13:52 UTC, shimotaroo commented on resources/views/welcome.blade.php
> +                    Laravel 共同開発
申し訳ありません！
ここ、コンフリクトの元になっちゃうので修正を戻しておいてくださいm(__)m

2021-01-12 13:52 UTC, shimotaroo commented on database/migrations/2021_01_11_110329_create_m_products_table.php
> +            $table->integer('user_id');
コメントの付け方NICEです！！

// TODO：m_usersテーブル完成し次第外部キー付与

とかでもいいですね！（修正不要ですが、共同開発ではTODOとか使うことがあるようです）

2021-01-12 13:57 UTC, hirotera commented on database/migrations/2021_01_11_110329_create_m_products_table.php
> +            $table->integer('user_id');
TODOの方がかっこいいですねw!次回からTODO使います!

2021-01-12 14:01 UTC, hirotera commented on resources/views/welcome.blade.php
> +                    Laravel 共同開発
不要箇所削除しました!

2021-01-12 14:04 UTC, shimotaroo approved these changes
バッチリです！！

2021-01-12 14:05 UTC, merged