検索->詳細 商品が存在しない場合の遷移実装（けーすけ）
quest-academia/yanbaru_ec_traning pull request #50
Opened 2021-01-11 10:52 UTC by keisuke-1-7

検索画面から詳細画面に遷移する際に、商品が存在しなかった場合の実装が抜けており、実装いたしました。
また、ルーティングファイルが少し乱れておりましたので、整理しております。
ご確認をお願いいたします。

2021-01-12 13:22 UTC, ryota100 commented
お疲れ様です。

うまく書けていると思います。
ただ、１点、iteminfo/10(商品がない番号)などとurlに直打ちした際に該当商品が見つからない旨の表示をが出るようしていただければと思います。

以上、よろしくお願いします。

2021-01-13 13:29 UTC, ryota100 reviewed
お疲れ様です。

修正バッチリです！

ただ、先ほどマージがあった関係で、コンフリクトが生じてますので、そちらの修正をお願いします。

2021-01-13 13:29 UTC, ryota100 commented on resources/views/item_notfound.blade.php
> +                {!! link_to_route('show', '商品検索画面', [], ['class' => 'btn btn-primary btn-lg']) !!}
こちらインデント右にずらすとより整理されて見えると思います。

2021-01-13 13:29 UTC, ryota100 commented on resources/views/searchproduct.blade.php
> +          {!! link_to_route('iteminfo', '商品詳細', ['id' => $product->id ], ['class' => 'btn btn-primary btn-sm']) !!}
こちらインデント右にずらすとより整理されて見えると思います。

2021-01-13 22:05 UTC, quest-academia requested changes
確認しました！

・りょうたさん指摘の箇所の修正
・僕の指摘の空行の削除

こちらだけお願い致します！
これ以外はOKです😊

2021-01-13 22:05 UTC, quest-academia commented on app/Http/Controllers/ProductController.php
> +
この空行は不要かと思います！

2021-01-13 22:05 UTC, quest-academia commented on app/Http/Controllers/CartController.php
> +
この空行は不要かと思います！

2021-01-14 14:41 UTC, ryota100 commented
改めてOKです！
ありがとうございます！

2021-01-14 21:48 UTC, quest-academia approved these changes
OKです！
マージしました😊
おつかれさまでした！

2021-01-14 21:48 UTC, merged