[add]ログイン者のロールによってログイン後の画面を出し分けた
quest-academia/yanbaru_ec_traning pull request #51
Opened 2021-01-11 14:01 UTC by Torippana

ユーザーのclassificationsのロール別にログイン後の遷移画面をだし分ける機能を追加しました。
遷移後の画面は別課題で作成すると思うのでルーティングだけ実装しました
ご確認よろしくお願いします。

2021-01-12 13:54 UTC, ryota100 reviewed
お疲れ様です。

管理者ログインの実装素晴らしいです✨
とても良いかと思います。
微細な点だけ指摘させていただきましたので、修正お願いします。

以上、よろしくお願いします。

2021-01-12 13:54 UTC, ryota100 commented on app/Http/Controllers/SellerController.php
> +        //
使ってないコメントアウトについて削除お願いします。

2021-01-12 22:47 UTC, quest-academia requested changes
確認しました！

Laravelの技術を理解して使われていて、とても素晴らしいと思います。

いくつか確認いただきたい点がありましたので、
コメントしました。

ご確認お願い致します😊

2021-01-12 22:47 UTC, quest-academia commented on app/Http/Controllers/Auth/LoginController.php
> +        $user_role_id = $this->guard()->user()->user_classification_id;
変数名は、今回はキャメルケースで統一する形なので、
原則キャメルケースでいきましょう！
（他の部分も修正願います！）

2021-01-12 22:47 UTC, quest-academia commented on app/Http/Middleware/RedirectIfAuthenticated.php
> +            $can_edit_flag = Auth::guard()->user()->user_classification_id;
ここの記述はとても素晴らしいと思います😊

変数名は、LoginController.phpと同じで、
$can_edit_flag ではなく
$userRoleId にした方が
統一性があるのではないでしょうか？

2021-01-12 22:47 UTC, quest-academia commented on app/Http/Controllers/Auth/LoginController.php
> +        if ($user_role_id == config('const.USER_CLASSIFICATIONS.SELLER') || $user_role_id == config('const.USER_CLASSIFICATIONS.ADMIN')) {
定数など使われていてとてもいいですね。

2021-01-12 22:47 UTC, quest-academia commented on app/Providers/AppServiceProvider.php
>      }
サービスプロバイダを使われていて、素晴らしいです！

2021-01-12 22:47 UTC, quest-academia commented on resources/views/layouts/seller_app.blade.php
> +
この辺りの空行が不要かなと思いますので、削除しましょう！

2021-01-12 22:47 UTC, quest-academia commented on resources/views/layouts/seller_app.blade.php
> +
この辺りの空行が不要かなと思いますので、削除しましょう！

2021-01-12 22:47 UTC, quest-academia commented on resources/views/seller/index.blade.php
> +
この辺りの空行が不要かなと思いますので、削除しましょう！

2021-01-13 13:17 UTC, quest-academia approved these changes
確認しました！
修正お疲れ様でした。OKです😊

2021-01-13 13:18 UTC, merged