Feature/juri/front order history　注文履歴（じゅり）
quest-academia/yanbaru_ec_traning pull request #52
Opened 2021-01-12 14:53 UTC by Juri-O

お世話になっております。
動作確認が終わりましたので、プルリクさせていただきました。
ご確認をよろしくお願いいたします。

2021-01-18 13:03 UTC, Juri-O commented
注文詳細のキャンセル仕様に伴い、注文履歴にもキャンセル表示が出るように追加しました。
注文がなかった場合の判定がうまく動作していなかったことが判明したため、修正を行いました。
ご確認をよろしくお願いいたします。

2021-01-18 13:58 UTC, shimotaroo requested changes
大変な処理だったと思いますが、よく書けていますね！
書き方に関して少しコメント入れさせていただきましたので確認お願いします😆

2021-01-18 13:58 UTC, shimotaroo commented on app/Http/Controllers/OrdersController.php
> +        $recentlyOrders = $user->orders()->where('order_date','>',$targetDate)->orderBy('order_date','desc')->paginate(15);
しっかり書けていますが、基本的にカンマのあとはスペースをつけましょう！

LaravelはPSR-2というコーディング規約を準拠しています。
http://www.infiniteloop.co.jp/docs/psr/psr-2-coding-style-guide.html

こちらのリンクから「カンマ」で検索すると以下の記載があります！
>また各カンマの後ろには１スペースおかなければなりません。

2021-01-18 13:58 UTC, shimotaroo commented on app/Order.php
> +    protected $fillable = ['user_id','order_date','order_number'];
これは修正不要かつ今回はこれで全く問題ないのですが、補足情報として

[ ]の中がもっと多くなったら

```
protected $fillable = [
    'user_id','order_date','order_number'
];
```

こんな風に書いても良いです！
※ちなみに僕は今回のケースでも上記の形で書きますw

2021-01-18 13:58 UTC, shimotaroo commented on app/OrderDetail.php
> +    protected $fillable = ['product_id','order_id','shipment_status_id','order_quantity'];
app/Order.phpと同じような書き方で書いてみましょう！

2021-01-18 13:58 UTC, shimotaroo commented on resources/views/shopping/order_history.blade.php
> +                                @endphp
今回は僕からは修正依頼は出しません（ゆうとさんが出すかもw）が、なるべくロジックはController or Modelに書くのが好ましいです！

あくまでViewは「表示するだけ」にするのがベストです！

2021-01-18 13:58 UTC, shimotaroo commented on app/Http/Controllers/OrdersController.php
> +    }
今回はそのままでも良いですが、本来は使わないメソッドは消す方がいいです！
頭に入れておいてください！

2021-01-19 09:18 UTC, yuto-ono commented on app/OrderDetail.php
> +    protected $fillable = ['product_id','order_id','shipment_status_id','order_quantity'];
この場合、私なら

```
protected $fillable = [
    'product_id',
    'order_id',
    'shipment_status_id',
    'order_quantity',
];
```

という感じで書きます。
行数が多くなりますが、見やすさの方が大事です！

2021-01-19 09:25 UTC, yuto-ono commented on resources/views/shopping/order_history.blade.php
> +                                @endphp
ゆーたろーさんのおっしゃる通りですが、今回、2重ループの複雑な処理をよく書けていますのでOKです！
余裕があれば、Controllerに38〜52行目あたりのロジックを移行する練習をしてみてもいいかもしれません！

2021-01-19 09:26 UTC, yuto-ono requested changes
基本的によくできています！
あとは少し意識するだけで劇的に読みやすいコードが書けますので、ぜひ意識してみてください ✨

2021-01-19 23:08 UTC, shimotaroo approved these changes
レビューしました！
問題ありません！
お疲れ様でした🙆‍♂️

2021-01-19 23:08 UTC, shimotaroo commented on app/Order.php
> +    ];
ここもapp/OrderDetail.phpと同じような書き方の方が良さそうですね！
今回は処理に影響しない単純な書き方の話なので修正は不要かと思いますが、app/OrderDetail.phpの書き方の方が可読性が高いということだけ頭に入れておいてください😆

2021-01-19 23:49 UTC, yuto-ono approved these changes
OKです！

2021-01-19 23:49 UTC, merged