出品者の商品一覧/検索画面の実装（たくみ）
quest-academia/yanbaru_ec_traning pull request #60
Opened 2021-01-16 13:29 UTC by takumi-isd

お疲れ様です。出品者の商品一覧/検索画面の実装が完了したので提出します。
ご確認よろしくお願い致します。

2021-01-16 16:33 UTC, ryota100 commented
お疲れ様です。
一点だけ指摘ですが、プラウザ上で、ログインすると、「出品者のページです」というページに遷移しますので、
画面遷移図の通り、商品一覧、検索画面に遷移される様に修正しましょう。

他追加されたコードなどは、うまく書けているかと思います✨

以上、よろしくお願いします。

2021-01-24 14:05 UTC, ryota100 commented
お疲れ様です。

管理者でのログイン時に、管理者用のログイン画面が表示されること、けーすけさんが実装された修正画面に遷移できることなど確認いたしました。emailのバリデーションも問題ありません。

OK！です。
よろしくお願いします。

2021-01-24 21:51 UTC, SekiYukihiro requested changes
確認してコメントしました！

Rule::unique('m_users')->ignore($user->id)
ここのバリデーション部分、なかなか実装が難しかったと思いますが、
よくたどり着かれたと思います✨

その他、主に細かい点ですが、修正頂きたい部分がいくつかありましたので
ご確認のほど宜しくお願い致します😊

2021-01-24 21:51 UTC, SekiYukihiro commented on app/Http/Controllers/SellerController.php
> +        }
こちらは、PSR-2のコーディング規約に基づき、下記のように書き直しましょう！

こちらのページを今一度見直してください✨
参考ページ: https://www.ritolab.com/entry/92

if (〜) {
}

2021-01-24 21:51 UTC, SekiYukihiro commented on app/Http/Controllers/SellerController.php
> +        }
こちらは、PSR-2のコーディング規約に基づき、下記のように書き直しましょう！

こちらのページを今一度見直してください✨
参考ページ: https://www.ritolab.com/entry/92

if (〜) {
}

2021-01-24 21:51 UTC, SekiYukihiro commented on app/Http/Requests/UserRequest.php
> +            'email' => ['required','string','email','max:50',Rule::unique('m_users')->ignore($user->id)],
Rule::unique('m_users')->ignore($user->id)
ここのバリデーション部分、なかなか実装が難しかったと思いますが、
よくたどり着かれたと思います✨

お疲れ様でした！

2021-01-24 21:51 UTC, SekiYukihiro commented on app/Http/Requests/UserRequest.php
> +            'phone_number' => ['required','numeric','digits_between:4,15'],
こちらだけでなく全体的に見直して欲しいのですが、
PSR-2のコーディング規約に基づき、カンマの後には必ずスペース１つを入れるようにしましょう！

こちらのページを今一度見直してください✨
参考ページ: https://www.ritolab.com/entry/92

2021-01-24 21:51 UTC, SekiYukihiro commented on app/Http/Requests/UserRequest.php
> +            'phone_number.digits_between' => '電話番号は4文字以上15文字以内で入力してください。'
'last_name.string' => '',
名前が文字列でなかった場合のバリデーション部分にも、適切な日本語メッセージを記述しましょう。

また、
last_nameとfirst_nameが同じ「名前」という名称で書かれていて違いが分かりませんので、
「姓」「名前」などの名称でバリデーションの記述を区別した方がいいかなと思いました！

2021-01-25 21:30 UTC, SekiYukihiro requested changes
良くなったと思うのですが、
修正いただいた部分でコーディング規約に沿えていない部分があったりしましたので
お手数ですが再度ご確認いただけますでしょうか？

宜しくお願い致します。

2021-01-25 21:30 UTC, SekiYukihiro commented on app/Http/Controllers/SellerController.php
> +        }
もう一度コーディング規約を見てください✨

ifのカッコの前後にはスペースが必要なはずです！

2021-01-25 21:30 UTC, SekiYukihiro commented on app/Http/Controllers/SellerController.php
> +        }
もう一度コーディング規約を見てください✨

ifのカッコの前後にはスペースが必要なはずです！

2021-01-25 21:30 UTC, SekiYukihiro commented on app/Http/Requests/UserRequest.php
> +            'last_name.string' => '文字列とし入力してください。',
文字列とし入力してください。

は日本語として変な気がするので

文字列を入力してください。

とかにしましょう✨
他の部分も同様です。

2021-01-27 22:25 UTC, SekiYukihiro approved these changes
OKです！
問題ないのでマージしました。

宜しくお願い致します😊

2021-01-27 22:25 UTC, merged