users関連テストデータ作成(miya)
quest-academia/yanbaru_ec_traning pull request #62
Opened 2021-01-18 10:14 UTC by miyazaki0505

ユーザー関連テストデータを作成いたしました。
ご確認の程よろしくお願いいたします。

2021-01-18 13:34 UTC, BGRyotaIto commented
お疲れ様です。

問題ありません。
OK！です✨
よろしくお願いします。

2021-01-18 13:40 UTC, shimotaroo requested changes
レビューしました！
内容は問題ありませんが、書き方のところで少しだけコメント入れていますのでご確認ください(^o^)

2021-01-18 13:40 UTC, shimotaroo commented on database/seeds/M_User_ClassificationsTableSeeder.php
> +            ],
'user_class〜'の部分はインデントを１つ下げた方が見やすくなりますよ！
database/seeds/M_Users_TableSeeder.phpと同じイメージです！

2021-01-20 00:21 UTC, shimotaroo approved these changes
バッチリです！
mergeします👌
お疲れ様でした！！！

2021-01-20 00:21 UTC, merged