Feature/gyagariko31/migration(gyagariko31)
quest-academia/yanbaru_ec_traning pull request #63
Opened 2021-01-18 11:49 UTC by gyagariko31

マイグレーションファイルの順番操作

2021-01-18 15:13 UTC, ryota100 commented
お疲れ様です。

マイグレーションファイルが、新たに作成した分と以前作成した分で2重に作成されているようです。
削除とリモート上に送られてないように注意の上pushください。
よろしくお願いします。

2021-01-19 15:28 UTC, ryota100 commented
お疲れ様です。

マイグレーションファイルと今ある範囲のサンプルデータが無事作成されることを確認しました。
OK!です。
よろしくお願いします。

2021-01-19 23:03 UTC, shimotaroo requested changes
1箇所だけ修正お願いします！
またコメントの付け方にもコメントしていますのでご確認お願いします！

2021-01-19 23:03 UTC, shimotaroo commented on database/migrations/2021_01_08_110329_create_m_products_table.php
> +            $table->increments('id');//bigIncrementsをincrementsに変更　型が合っていない的なエラーが出たため
今回はOKとしますが、実務では上記のように「自分用のメモ代わりのコメント」は残さない方が好ましいので頭に入れておくだけしておいてください！
（他の箇所も同様です）

2021-01-19 23:03 UTC, shimotaroo commented on database/migrations/2021_01_08_110329_create_m_products_table.php
> +            //$table->integer('user_id'); カラム重複のエラーが出たためコメントアウト
不要なコメントアウトは消しておきましょう！
（こちらは修正お願いします）

2021-01-20 13:28 UTC, shimotaroo approved these changes
バッチリです！
お疲れ様でした！

2021-01-20 13:29 UTC, merged