バック側の商品修正画面・削除機能 / エラー表示修正の実装
quest-academia/yanbaru_ec_traning pull request #65
Opened 2021-01-20 01:17 UTC by keisuke-1-7

バック側の商品修正画面・削除機能の実装です。
他メンバーさんとコントローラ名が異なると思います、PR作成の段階で変更しておいた方が良いでしょうか？

また、エラーメッセージの表示修正の実装もこちらで行いましたが、ブランチを切るべきだったかもしれません。
よろしくお願いいたします。

2021-01-20 01:20 UTC, keisuke-1-7 commented on resources/lang/ja/validation.php
> +<?php
こちら、エラーメッセージ表示に関する修正です

2021-01-20 14:40 UTC, ryota100 commented
お疲れ様です。

編集や削除など、綺麗に実装されていて素晴らしいです😊

１点だけ、updateするときにバリデーションが効いておらず、エラー画面に飛んでしまいましたので、バリデーションをを入れましょう。
できればこちらのフォームリクエストでやってみてください。
https://laraweb.net/knowledge/2156/

よろしくお願いします。

2021-01-22 14:25 UTC, keisuke-1-7 commented on app/Http/Requests/CreateProductRequest.php
> +        ];
こちらバリデーションの記載ですが、リレーションのあるフォーム（代表してcategory_id）では　”exists:m_categories,id”をつけております。
必要かどうか判断がつきませんでしたので、念のため記載しております。　

2021-01-22 16:37 UTC, ryota100 commented
お疲れ様です。

フォームリクエストでのバリデーションの導入確認しました。
日本語でのバリデーションメッセージも出ており、OKです✨

よろしくお願いします。

2021-01-22 23:00 UTC, SekiYukihiro commented on app/Http/Controllers/BackProductController.php
> +            'product_status_id' => $product_status_id,
他の方のコードを観ていると、おおむね、キャメルケースで変数名を記述されていますので
こちらも全体的にキャメルケースで記述しましょうか。
https://github.com/quest-academia/yanbaru_ec_traning/blob/develop_alpha/app/Http/Controllers/ProductController.php

$category_name（スネークケース）ではなく、$categoryName（キャメルケース）で記述する形です。

2021-01-22 23:00 UTC, SekiYukihiro commented on app/Http/Controllers/BackProductController.php
> +            'product_status_id' => $product_status_id,
あと、ここはインデントをスペース4つ分追加して下げるのが適切です✨

2021-01-22 23:00 UTC, SekiYukihiro commented on app/MProduct_status.php
> +}
モデルはコードレビュー基準で命名規則が決まっておりまして、
クラス名 はUpperCamelCaseのような アッパーキャメルケースで記述しましょう✨

改めて下記コーディング規約や
前にPDFでお渡ししたコードレビュー基準書を確認しておいてください😊

 https://www.ritolab.com/entry/92

2021-01-22 23:00 UTC, SekiYukihiro commented on app/MProduct_status.php
> +}
クラス名 （これでいうと、MProduct_statusのところ）は
UpperCamelCaseのような アッパーキャメルケースで記述しましょう✨

改めて、前にお見せした、下記コーディング規約や
PDFでお渡しした、コードレビュー基準を確認してください✨

https://www.ritolab.com/entry/92

2021-01-22 23:25 UTC, SekiYukihiro requested changes
確認しました！

コードも読みやすく意味のある纏まりごとに記述されていたり、
フォームリクエストの中のバリデーションの記述も丁寧で
全体的にクオリティが高いと思いました😊

いくつか変更して欲しい箇所がありましたので、
ご確認お願い致します✨

2021-01-22 23:25 UTC, SekiYukihiro commented on app/MSales_status.php
> +}
クラス名 （これでいうと、MSales_statusのところ）は
UpperCamelCaseのような アッパーキャメルケースで記述しましょう✨

改めて、前にお見せした、下記コーディング規約や
PDFでお渡しした、コードレビュー基準を確認してください✨

https://www.ritolab.com/entry/92

2021-01-22 23:25 UTC, SekiYukihiro commented on app/Http/Controllers/BackProductController.php
> +            'product_status_id' => $product_status_id,
ここは、インデントをもう１つ（＋スペース４つ分）追加すべきところですね。

2021-01-22 23:25 UTC, SekiYukihiro commented on app/Http/Controllers/BackProductController.php
> +        $category_id = $product->category_id;
下記のリンクの通り、変数名の他の方の記述が、
スネークケースではなく、キャメルケースになっています。

$category_name　ではなく、　$categoryName

可能であれば、プロジェクトで統一感を持たせた方が良いので
全てキャメルケースに統一して頂けると良いかなと思います😊

ここ以外の部分も、スネークケースになっていますので、
可能であれば、全てキャメルケースに変更しましょう！

https://github.com/quest-academia/yanbaru_ec_traning/blob/develop_alpha/app/Http/Controllers/ProductController.php

2021-01-22 23:25 UTC, SekiYukihiro commented on app/Http/Controllers/BackProductController.php
> +        $categories = $category->getLists();
下で静的に関数を呼び出しているのであれば、
ここも同じく静的に関数を呼び出しましょう。

$category = MCategory::getLists();

2021-01-22 23:25 UTC, SekiYukihiro commented on app/Http/Controllers/BackProductController.php
> +        $sale_statuses = $sale_status->getLists();
下で静的に関数を呼び出しているのであれば、
ここも同じく静的に関数を呼び出しましょう。

2021-01-22 23:25 UTC, SekiYukihiro commented on app/Http/Controllers/BackProductController.php
> +        $product_statuses = $product_status->getLists();
下で静的に関数を呼び出しているのであれば、
ここも同じく静的に関数を呼び出しましょう。

2021-01-22 23:25 UTC, SekiYukihiro commented on app/Http/Requests/CreateProductRequest.php
> +        ];
フォームリクエスト、きちんと実装できていて、とても良いですね😊

existsは、テーブルに、カラム名（この場合入力されたID）が存在するか確認するためのバリデーションなので
この記述方法で良いと思いますよ！
この辺り、きちんと実装されない方も多いので、
配慮がとても素晴らしいと思います😊

2021-01-22 23:25 UTC, SekiYukihiro commented on resources/lang/ja/validation.php
> +<?php
日本語化にきちんとされていて、完璧だと思います！

2021-01-23 15:20 UTC, keisuke-1-7 commented on app/Http/Controllers/BackProductController.php
> +        $categoryName = MCategory::find($product->category_id)->category_name;
こちら、せきさんにご提案いただいたコードでエラーが出たため、このように記載しましたがよろしいでしょうか？
MCategoryモデルからの戻り値が$categoriesですが、「$category = MCategory::getLists();」だと$categoriesが定義できないのかと感じました。

2021-01-23 15:22 UTC, keisuke-1-7 commented on app/Http/Requests/CreateProductRequest.php
> +        ];
解説ありがとうございます！
承知いたしました！今後も丁寧なコーディングを心がけます！

2021-01-23 15:22 UTC, keisuke-1-7 commented on app/Http/Controllers/BackProductController.php
> +            'product_status_id' => $product_status_id,
承知いたしました！
他の部分も修正いたします！

2021-01-23 20:56 UTC, SekiYukihiro approved these changes
修正お疲れ様でした！
問題ありませんので、こちらでマージしました:blush:

ご確認宜しくお願い致します！！

2021-01-23 20:56 UTC, SekiYukihiro commented on app/Http/Controllers/BackProductController.php
> +        $categoryName = MCategory::find($product->category_id)->category_name;
すみません！

これは単に僕の記載ミスのため、
$categoryではなく$categoriesにして頂く判断で大丈夫です😊

2021-01-23 20:56 UTC, merged