Feature/tetsuyoshi/item details
quest-academia/yanbaru_ec_traning pull request #69
Opened 2021-01-23 14:53 UTC by yoshitaro-yoyo

商品詳細表示画面です

2021-01-23 23:16 UTC, shimotaroo approved these changes
レビューしました！
全て処理内容には関係ないコメントなので修正は不要です！
（修正しても問題ありませんがw）

大変な処理だったと思いますが、よくできていると思います！

2021-01-23 23:16 UTC, shimotaroo commented on app/Category.php
> +    }
app/Product.phpでは以下のように引数に指定するクラスの書き方がネームスペースの書き方になっているので統一した方が良いと思います。

```
    //カテゴリーIDに関連する商品カテゴリー情報を取得する
    public function category()
    {
        return $this->belongsTo('App\Category');
    }
```

ドキュメントを見た感じ上記の方がいいですね！

2021-01-23 23:16 UTC, shimotaroo commented on app/Product.php
> +    }
belongsToの場合は`users`ではなく`user`にした方が良いですね！

2021-01-23 23:16 UTC, shimotaroo commented on app/User.php
> +
ここはVSCodeのGitの拡張機能で差分として認識されていましたか？
もしされているようでしたらこのような本来不要な修正文はコミットされない方が良いです！
（このファイルの変更履歴に残り続けてしまうので...）

2021-01-23 23:16 UTC, shimotaroo commented on app/User.php
>          return $this->hasMany(Order::class);
ここのクラスの指定はドキュメント通りに書いた方が良いと思いますね！

2021-01-23 23:16 UTC, shimotaroo commented on resources/views/products/no_cart_list.blade.php
> +@endsection
今回はこちらの仕様で画面ごと分けましたが、

・カートに商品がある場合
・カートに商品がない場合

で場合わけして1つのbladeで完結させるのも良いですね！

2021-01-23 23:16 UTC, shimotaroo commented on resources/views/products/prodInfo.blade.php
> +@extends('layouts.app')
このコードのコメントではないですが、
resources/views/products/prodInfo.blade.phpではなく
resources/views/products/productInfo.blade.php
で良いと思いますw

2021-01-23 23:16 UTC, shimotaroo commented on resources/views/products/cartlist.blade.php
> +                                        @endif
ここって

・@if〜@elseがない
・isset($data['product_name']がfalseになる条件（$data['product_name']がnullとか）

だと上手く動作しませんでした？？
もし上手く行くなら少し冗長になるかな...とも思いました

2021-01-23 23:17 UTC, shimotaroo commented
@yoshitaro-yoyo 

コンフリクトしているので解消だけ必要でした！

2021-01-24 08:27 UTC, yoshitaro-yoyo commented on resources/views/products/cartlist.blade.php
> +                                        @endif
{{ isset($data['product_name']) ? $data['product_name']:'null' }}

で表示できました！三項演算子というのですね！有難うございます！

2021-01-26 12:55 UTC, yuto-ono requested changes
難しいところを良く実装されました！
不要なforeachを消すのだけお願いします 🙏

2021-01-26 12:55 UTC, yuto-ono commented on resources/views/products/cartlist.blade.php
> +                                        @endif
null合体演算子を使うとスッキリします！　参考までに！
`{{ $data['product_name'] ?? '' }}`

2021-01-26 12:55 UTC, yuto-ono commented on routes/web.php
> +})->name('noProduct');
（今回は修正不要ですが）
こちらはルーティングに書くのではなく、なるべくコントローラーに書いた方が良いですね。
あるいはviewメソッドを使っても大丈夫です。
`Route::view('/no-product', 'products/no_product');`
理由は、デプロイ後のパフォーマンスに影響するからです。
https://readouble.com/laravel/5.8/ja/deployment.html

2021-01-26 12:55 UTC, yuto-ono commented on resources/views/products/cartlist.blade.php
> +                                    foreach ($cartData as $key => $data)
このforeachって要らないですよね？（消し忘れ？）
無駄に処理を繰り返してしまうので消しましょう！

2021-01-27 00:24 UTC, yoshitaro-yoyo commented on resources/views/products/cartlist.blade.php
> +                                        @endif
有難うございます！早速調べてみます！

2021-01-29 02:22 UTC, yuto-ono approved these changes
OKです！　お疲れ様でした！

2021-01-29 02:22 UTC, merged