add:DB構築-products関連(けーすけ)
quest-academia/yanbaru_ec_traning pull request #7
Opened 2020-11-22 14:08 UTC by keisuke-1-7

たくみさんの実装予定である仕入れテーブル（t_purchases）は含んでおりません。

特に各テーブルのテータ型のご確認をお願いいただけますでしょうか。
また販売状態と商品状態のテストデータ項目に何を入れるべきか迷いましたので、そちらもご確認いただければ幸いです。

2020-11-22 14:14 UTC, keisuke-1-7 commented on database/migrations/2020_11_22_120214_create_m_products.php
> +            $table->increments('product_id');
型や修飾子のご確認をお願いいたします。

2020-11-22 14:15 UTC, keisuke-1-7 commented on database/migrations/2020_11_22_120214_create_m_products.php
> +        });
型や修飾子のご確認をお願いいたします。

2020-11-22 14:16 UTC, keisuke-1-7 commented on database/seeds/M_Products_StatusesSeeder.php
> +         ]);
入れるべきテストデータの内容に迷いましたが、こちらでよろしいでしょうか？

2020-11-22 14:17 UTC, keisuke-1-7 commented on database/seeds/M_Sales_StatusesSeeder.php
> +    }
入れるべきテストデータの内容に迷いましたが、こちらでよろしいでしょうか？

2020-11-23 05:18 UTC, ryota100 reviewed
お疲れ様です。
データ型など全体を通して確認させていただきました。
問題なく書けておりましたので、しっかり身に付けられたのかと思います。
特に外部キー制約について、試行錯誤して書かれたかと思いますので、とても素晴らしいと思います。

数点指摘させて頂いた場所について修正をよろしくお願いします。

2020-11-23 07:31 UTC, keisuke-1-7 commented on database/seeds/M_Sales_StatusesSeeder.php
> +    }
変更内容→ご提示いただいた見本通りに作成しました。

2020-11-23 07:31 UTC, keisuke-1-7 commented on database/seeds/M_Products_StatusesSeeder.php
> +         ]);
変更内容→ご提示いただいた見本通りに作成しました。

2020-11-23 09:43 UTC, SekiYukihiro commented on database/migrations/2020_11_21_234119_create_m_categories.php
> +            $table->string('category_name',32);
今回の共同開発は、PSR-2というコーディング規約に乗っ取っています。
（以前、PDFでSlackに記載した資料にも書かれています）
コーディング規約参考資料：https://www.ritolab.com/entry/92

規約上、「,」カンマの後ろには、スペースを１つ入れるのがルールとなっておりますので、
こちらだけでなく全体的にスペースがない部分がありますので、
そちらを修正ください✨

2020-11-23 09:43 UTC, SekiYukihiro requested changes
確認いたしました！
とてもよく配慮されて作れていると思います😊

そして、りょうたさんも書かれてましたが
データ内容が美味しそうですね。。。！

細かい記述上のルールについて、１点だけ記載致しましたので
お手数ですがご訂正お願いいたします！

2020-11-24 09:30 UTC, ryota100 commented
お疲れ様です✨
コーディング規約について、修正がなされていることを確認致しました。
以上、よろしくお願い致します。

2020-11-24 12:25 UTC, SekiYukihiro approved these changes
問題ないのでマージさせて頂きます！
お疲れ様でした✨

2020-11-24 12:26 UTC, merged