ユーザー登録get,post作成
quest-academia/yanbaru_ec_traning pull request #70
Opened 2021-01-24 07:03 UTC by gyagariko31

2021-01-24 13:28 UTC, ryota100 reviewed
お疲れ様です。

ユーザー登録とバリデーションメッセージなど確認しました。
バリデーションの日本語化について、別でコメント書きましたので確認ください。

それと、もう一点ですが、
ページを２分割表示してみていた時に、以下の画像のように姓や名がフォームと重なりましたので、paddingなどで文字の位置を調整していただければと思います。

あと、今後のためや周りの共同開発者に一体何をしたのか知らせる上でも、プルリク時には、自分が何をしたのか相手に分かるように書くようにしていきましょう。

実装面では基本問題なく仕上げていただいたと思います✨
以上、指摘した点についてよろしくお願いします。

![スクリーンショット 2021-01-24 22 23 01](https://user-images.githubusercontent.com/64177062/105631631-ba5faa80-5e92-11eb-9459-96b836ccaf81.png)

2021-01-24 13:28 UTC, ryota100 commented on resources/lang/en/validation.php
>  ];
validationの日本語化もされてて素晴らしいです✨

２点気になったこととして、
①日本語化ファイルですので、jaの階層のしたに入れた方が一般的かと思います。
resources/lang/en/validation.phpから、
resources/lang/ja/validation.phpへ。

②また、日本語にはなっているものの、
郵便番号のバリデーションメッセージとして、
郵便番号では、 郵便番号 7 数値　というように出ており、どういう意味かちょっと分かりづらいかなと思います。
せっかく日本語化にされているので、
https://readouble.com/laravel/5.8/ja/validation-php.html?header=%25E8%25AA%25AC%25E6%2598%258E
のリンクを参考ください。
これを使って、適宜カスタマイズする方向で良いかと思います。

２点の修正をお願いします。

2021-01-24 20:49 UTC, gyagariko31 commented
お疲れ様です　バリデーション、フォームの重なり　を修正いたしました。お時間ある際、ご確認の程よろしくお願いいたします。

2021-01-25 14:40 UTC, ryota100 commented
お疲れ様です。

修正内容確認しました。
OK！です。
よろしくお願いします🤲

2021-01-26 00:46 UTC, shimotaroo requested changes
レビューさせていただきました！！

全体的によくできているなと思います！
バリデーションメッセージ周りだけ再度確認ください😁

2021-01-26 00:46 UTC, shimotaroo commented on app/User.php
> +
今回は修正不要ですが、このような不要な修正は極力なくすように意識していきましょう！

2021-01-26 00:46 UTC, shimotaroo commented on resources/lang/ja/validation.php
> +    'attributes' => [],
ここにresources/lang/en/validation.phpの内容を書いた方が良いと思います。
というかこの状態でバリデーションメッセージは名前や住所など日本語で出ますか？

2021-01-26 00:46 UTC, shimotaroo commented on resources/lang/en/validation.php
>  ];
config/app.phpに
```
locale => 'ja'
```

にしているので今回はenは使わなくて良いと思うのでここの修正文は元に戻しておいて良いかと思います！

2021-01-26 09:51 UTC, gyagariko31 commented on resources/lang/ja/validation.php
> +    'attributes' => [],
バリデーション確認で日本語のメッセージが普通に表示されたので問題ないかと思いました

2021-01-26 10:08 UTC, gyagariko31 commented
お疲れ様です　enファイルのバリデーションメッセージを戻し、‘attributes’ => [],内をjaファイルに移行　いたしました。お時間ある際、ご確認の程よろしくお願いいたします

2021-01-26 13:03 UTC, shimotaroo approved these changes
OKです！
お疲れ様でした😆

2021-01-26 13:03 UTC, merged