出品者画面商品追加機能実装（カトウマコト)
quest-academia/yanbaru_ec_traning pull request #77
Opened 2021-01-30 04:06 UTC by Torippana

よろしくお願いします

2021-01-30 06:55 UTC, BGRyotaIto commented
お疲れ様です。
実装確認しました。

管理者側から出品できるようになっていて、とてもいいですね😊

一点、僕の方のプラウザで、管理者でのログイン時に、
エラー文
Route [seller_search] not defined. (View: /var/www/html/resources/views/seller/seller_search_product.blade.php)
とでますので、修正の方、よろしくお願いします。

2021-01-30 06:56 UTC, BGRyotaIto commented on app/Http/Controllers/BackProductController.php
> +            return redirect()->route('back_product_create');
保存できているかどうかでフラッシュメッセージの表示をだし分けるのは素晴らしいですね✨

2021-01-30 06:58 UTC, ryota100 reviewed
お疲れ様です。 実装確認しました。
管理者側から出品できるようになっていて、とてもいいですね😊
一点、僕の方のプラウザで、管理者でのログイン時に、 エラー文 Route [seller_search] not defined. (View: /var/www/html/resources/views/seller/seller_search_product.blade.php) とでますので、修正の方、よろしくお願いします。

2021-01-30 06:58 UTC, ryota100 commented on app/Http/Controllers/BackProductController.php
> +            };
保存できているかどうかでフラッシュメッセージの表示をだし分けるのは素晴らしいですね✨

2021-01-30 21:47 UTC, SekiYukihiro requested changes
見させていただきました。
全体的に、とても綺麗に書けていると思います！

いくつか細かい点で確認したいことを書きましたので
お手数ですが、ご確認お願い致します😊

2021-01-30 21:47 UTC, SekiYukihiro commented on app/Http/Controllers/BackProductController.php
> +        $fail    = '0';
初期化されたこちらの値ってどこかで使われていますか？

2021-01-30 21:47 UTC, SekiYukihiro commented on app/Http/Controllers/BackProductController.php
> +        if ($user_id) {
非常に細かいレベルの話ですが、
$user_idの変数を使うなら、ここも他と統一して、
$userIdとキャメルケースにしましょう✨

2021-01-30 21:47 UTC, SekiYukihiro commented on app/Http/Controllers/BackProductController.php
> +        if ($user->id) {
ユーザがログインしているのなら、
$user->idはかならず存在するかと思うのですが、
ここでuser->idが存在するかどうか判定されている理由は何かありますでしょうか？

2021-01-30 21:47 UTC, SekiYukihiro commented on app/Http/Controllers/BackProductController.php
> +            $result = MProduct::create($data);
create関数を活用されていて、良いですね！

2021-01-31 03:39 UTC, ryota100 commented
お疲れ様です。
プラウザでエラーのあった件の修正確認しました✨

2021-01-31 21:13 UTC, SekiYukihiro approved these changes
OKです！

問題ないのでマージしました😊
宜しくお願いいたします！

2021-01-31 21:13 UTC, merged