カート機能実装
quest-academia/yanbaru_ec_traning pull request #78
Opened 2021-01-30 17:04 UTC by TAROTH666

カート機能、購入完了画面への遷移、注文のDBに登録する機能の実装が完了致しました。

ご確認よろしくお願い致します！

2021-01-31 11:04 UTC, ryota100 commented
お疲れ様です。
ご説明いただいた、コンフリクト解消の作業内容としては、大丈夫かと思います。

ただ、僕の方のプラウザで確認しようとすると、
ログイン時
Call to undefined method App\MCategory::getLists()

seederデータ作成時
Base table or view not found: 1146 Table 'yanbaru_ec_traning.t_orders_details' doesn't exist (SQL: insert into `t_orders_details` (`products_id`, `order_id`, `shipment_status_id`, `order_detail_number`, `order_quantity`, `shipment_date`) values (1, 1, 1, 1, 2, 2021-02-01 19:50:43))

とそれぞれエラーが起こりましたので、コンフリクト時に、間違いがあったのだと思います。

TAROさんの画面で、動作に支障がないように、修正取り組んでください。
なかなか難しいですが、develop_alphaブランチとくらべたり、エラー文から潰したりしていくの必要になってくると状態ですね。

2021-02-01 14:22 UTC, ryota100 commented
お疲れ様です。

確認が遅くなり申し訳ありません。
コードも難しい実装の中、素晴らしいと思います😊

プラウザとコードについて、実装確認しました。

数点、修正や確認事項です。

１点目
Call to undefined method App\MCategory::getLists()
のところが、まだ出ました。今回は、MCategory.phpにgetLists()を加えて、取り急ぎプラウザで確認しただけなので、そちらもう一度、確認ください。
本当は、getCategories()でしたら、controllerのgetListsと書いてあるところを適宜修正する必要があるかと思います。

２点目
dd();がコメントアウトでたくさん書いてある件について、今後確認用にあえて残されたということでよかったでしょうか？(少し気になってしまって)

３点目
これは、報告レベルですが、注文情報が、DBには保存されるものの注文履歴に反映されなかったので、その点、また修正いただければと思います。(注文履歴との絡みもあるかと思うので、今実装じゃなくて良いと思ってます)

以上、全体的に、素晴らしいと思いますが、数点確認ください🤲

2021-02-04 13:42 UTC, ryota100 commented
お世話になっております。

修正と無事動くこと確認いたしました。問題ありません

①
修正確認できました。こちらも動作に異常ありません

②
ddの件、デバックのためやアピールのこと了解しました。ちょっと気になったので指摘しましたが、個人的にはいい取り組みだと思ってます。

③
注文履歴反映されない件、今動作確認したら、反映されました。すいません、僕の方がおかしかったのかもです
以上、よろしくお願いします。

2021-02-04 22:58 UTC, quest-academia requested changes
確認しました😊
コードを読んでいて、試行錯誤して書かれたというのが伝わってきました！！

最高に難しい実装でしたが、よく乗り越えられたと思います。
本当にお疲れ様でした！

ロジックもご自分でしっかり考えられていて問題ないと思います。
なので、細かい点だけを記述しましたので、ご確認の上、可能であれば修正頂けますでしょうか？


また、dd()コメントアウトをあえて残しているということですが、
確かに「試行錯誤の結果」が見えて良い部分もあるのですが、
コードの可読性が下がって、
採用担当者がコードを読むのを諦めてしまうという要因にもなりうるかと思いました💦

最終的には残してもOKかと思いますが、
個人的には全体的に消した方がみやすいかなと思いました！

2021-02-04 22:58 UTC, quest-academia commented on app/Http/Controllers/CartController.php
> +            //session情報にcartDataという連想配列が「有る」場合、情報取得
このコメントアウトを書くとすれば、

```
//session情報にcartDataという連想配列が「無い」場合
if (!$request->session()->has('cartData')) {
      //商品情報の配列 cartData(key名)に、$cartData(配列)をSessionに追加
      $request->session()->push('cartData', $cartData);
//session情報にcartDataという連想配列が「有る」場合、情報取得
} else {
```

このように書いた方が、ifとelseで対になって見やすいと思います！

2021-02-04 22:58 UTC, quest-academia commented on app/Http/Controllers/CartController.php
> +            $flag = false;
フラグを使われていて、素晴らしいですね！

2021-02-04 22:58 UTC, quest-academia commented on app/MProduct.php
> +    public function getCategories()
商品テーブルから商品の値段と名前を取り出しているのに、
getCategories()というメソッド名だとおかしい気がするので
（カテゴリーテーブルとメソッド名が同じでややこしいかなと）
可能であれば、名称を変えましょう！

2021-02-04 22:58 UTC, quest-academia commented on resources/views/cartlist.blade.php
> +                {!! Auth::user()->first_name !!}
Viewが全体的に、インデントが２スペース分になっていますので、
コーディング規約に基づいて、インデントを４スペース分に変更しましょう✨

他のViewも同様です！😊

2021-02-05 03:10 UTC, SekiYukihiro approved these changes
OKです！

問題ないので、マージしました😊
本当にお疲れ様でした‼️

2021-02-05 13:49 UTC, quest-academia approved these changes
マージしました！

2021-02-05 13:49 UTC, merged