Feature/katomakoto/create orders tables
quest-academia/yanbaru_ec_traning pull request #8
Opened 2020-11-23 05:00 UTC by Torippana

orders関連のマイグレーションファイルとシーダーファイルができましたのでご確認お願いいたします。

2020-11-23 05:03 UTC, Torippana commented on database/migrations/2020_11_21_151942_create_t_orders_details_table.php
> +            // $table->foreign('shipment_status_id')
外部キーですが、他の方が作るテーブルがまだ存在しないので設定できないのでいったんコメントアウトしてあります。
（連携対象の親テーブルが存在しない時は子テーブルからの外部キー設定はできない認識でよろしいのでしょうか？）

2020-11-23 09:28 UTC, ryota100 reviewed
お疲れ様です。
確認しまして、全体通して問題ありません。１点だけ変更点を記入しました。
seederファイルの書き方も素晴らしいです。
力があるお方と思いますので、今後、共同開発者にコメントアウトでどのような記述をしているかを書いていくとより素晴らしいと思います。
以上になります。よろしくお願い致します。

2020-11-23 09:28 UTC, ryota100 commented on database/migrations/2020_11_20_032020_create_m_shipments_statuses_table.php
> +            $table->increments('shipment_status_id');
PKについて
プライマリーキーは、idとした方が良いので、大変お手数となるのですが
shipment_status_id→idに変更お願いします。
以下他のテーブルの
・ordersテーブル
・orders_detailsテーブル
についてもidに変更お願いします。

2020-11-23 09:54 UTC, SekiYukihiro commented on database/migrations/2020_11_21_064840_create_t_orders_table.php
> +        Schema::disableForeignKeyConstraints();
外部キー制約を一時的に無効化されていて素晴らしいですね✨
とてもテクニカルでいいと思います😊

2020-11-23 10:00 UTC, SekiYukihiro commented on database/seeds/T_OrdersDetailsTableSeeder.php
> +        //
コメントアウトの記述漏れでしょうか？

2020-11-23 10:01 UTC, SekiYukihiro commented on database/seeds/M_ShipmentsStatusesTableSeeder.php
> +        //
コメントアウトの記述漏れでしょうか？

2020-11-23 10:03 UTC, SekiYukihiro requested changes
素晴らしい出来だと思います😊

繰り返し部分をforeach,for文を使われていたり、
外部キー制約を一時的に解除する方法を記述されていたり、
とてもテクニカルで良いと思います！

コメントアウト部分の記述だけ、宜しくお願い致します😊

2020-11-23 10:03 UTC, SekiYukihiro commented on database/seeds/T_OrdersTableSeeder.php
> +        //
コメントアウトの記述漏れでしょうか？

2020-11-23 10:07 UTC, SekiYukihiro commented on database/migrations/2020_11_20_032020_create_m_shipments_statuses_table.php
> +            $table->string('shipment_status_name',32);
今回の共同開発は、PSR-2というコーディング規約に乗っ取っています。
（以前、PDFでSlackに記載した資料にも書かれています）
コーディング規約参考資料：https://www.ritolab.com/entry/92

規約上、「,」カンマの後ろには、スペースを１つ入れるのがルールとなっておりますので、
こちらご修正ください✨

2020-11-23 10:08 UTC, SekiYukihiro requested changes
「,」カンマの後ろには、スペースが必要という点だけ、
追記しました。

合わせてご確認お願い致します❗️

2020-11-23 14:53 UTC, ryota100 commented
お疲れです。
カンマの後ろの、スペース、誤字の削除、コメントの記載、idへの変更について確認しました。
外部キー参照の記述について変更が生じたと思いますので、その点指摘させていただきました。
よろしくお願いします。

2020-11-24 10:53 UTC, ryota100 commented
修正確認しました。
一点おそらく、テーブルやシーダー自体は作成できているかと思うのですが、外部キーの関連ができていないところがありましたので、そちらについて指摘いたしました。
確認よろしくお願います。

2020-11-24 12:47 UTC, SekiYukihiro approved these changes
問題ないので、マージします！
お疲れ様でした✨

2020-12-05 22:12 UTC, SekiYukihiro approved these changes
最適化、ありがとうございます！
（マージの漏れがあり、失礼しました）

また、内容確認しまして
問題ないかと思いますので、マージさせて頂きました😊

引き続き、宜しくお願い致します❗️

2020-12-05 22:13 UTC, merged