Feature/gyagariko31/user edit
quest-academia/yanbaru_ec_traning pull request #86
Opened 2021-02-15 06:12 UTC by gyagariko31

お疲れ様です　ユーザ情報修正画面　を作成いたしました。お時間ある際、ご確認の程よろしくお願いいたします。

2021-02-15 13:52 UTC, ryota100 reviewed
お疲れ様です。

処理自体は、問題ないです✨

編集時にページ遷移しないこと
フラッシュメッセージの利用をお勧めすること
について指摘させていただきました。

また、ユーザー情報を見た時
氏名が逆になっていたこと、
住所が一桁になってしまう点がありましたので、seederデータを修正された方が見た目綺麗になるかと思います。
以上、宜しくお願いします。

![スクリーンショット 2021-02-15 22 50 58](https://user-images.githubusercontent.com/64177062/107954794-45d6e200-6fe0-11eb-90a9-dc2dcbf05d93.png)

2021-02-15 13:52 UTC, ryota100 commented on app/Http/Controllers/UserInformationController.php
> +            return back();
画面遷移図の通り、ユーザー情報を修正したら、ユーザ情報照会画面へ遷移するようにしましょう。

2021-02-15 13:52 UTC, ryota100 commented on app/Http/Controllers/UserInformationController.php
> +        return redirect('/');
削除できたか分かりづらいので、以下リンクのようなフラッシュメッセージを使って、会員情報を削除しました。などと表示するとよりいいです。
https://qiita.com/usaginooheso/items/6a99e565f16de2f9ddf7

2021-02-16 07:32 UTC, gyagariko31 commented
お疲れ様です　ご指摘いただいた点　を修正いたしました。お時間ある際、ご確認の程よろしくお願いいたします。

2021-02-16 13:25 UTC, ryota100 commented
お疲れ様です。
修正指摘した点、どれもしっかり修正されていて、いいですね✨

OKです！
宜しくお願いします。

2021-02-16 22:35 UTC, shimotaroo requested changes
フラッシュメッセージ、良いですね😁

今のままでも処理は動くので良いのですが、より良いコードにするためにコメントしましたので修正してみてください！！

2021-02-16 22:35 UTC, shimotaroo commented on app/Http/Controllers/UserInformationController.php
> +
不要な改行（空行？）は消しておきましょう！

2021-02-16 22:35 UTC, shimotaroo commented on app/Http/Controllers/UserInformationController.php
> +            return redirect()->action('UserInformationController@show', ['id' => $user->id]);
インデントが揃っていないので合わせましょう！

```
return redirect()->action('UserInformationController@show', ['id' => $user->id]);
```

はこれで処理的には問題ないのですが、コード量が少ない

```
return redirect()->route('****');
```

に変更してみてください！
https://readouble.com/laravel/6.x/ja/helpers.html?header=redirect()

2021-02-16 22:35 UTC, shimotaroo commented on app/Http/Controllers/UserInformationController.php
> +
不要な改行（空行）は消しておきましょう！

2021-02-16 22:35 UTC, shimotaroo commented on app/Http/Controllers/UserInformationController.php
> +        $user->delete();
ここは1行で

```
$user = User::find($id)->delete();
```

こう書いた方がスッキリしますよ！

2021-02-16 22:35 UTC, shimotaroo commented on resources/views/commons/header.blade.php
> +                        <a class="nav-link active" href="{{ action('UserInformationController@show', ['id' => Auth::user()->id]) }}">ユーザ情報</a>
ここも`action`ではなく`route`で書いてみてください！

2021-02-16 22:35 UTC, shimotaroo commented on resources/views/user_information.blade.php
> +      <a class="btn btn-primary" href="{{ action('UserInformationController@edit', ['id' => Auth::user()->id]) }}">修正/退会する</a>
ここもせっかくなので`action`ではなく`route`で書いてみてください！

2021-02-16 22:35 UTC, shimotaroo commented on routes/web.php
> +    // ユーザー情報編集
このルーティングは編集だけの目的ではない点からこのコメントは誤解を招く可能性があるので、コメントをつけるのであれば見直してみてください！

2021-02-19 07:00 UTC, gyagariko31 commented
お疲れ様です　ご指摘いただいた点　を修正いたしました。お時間ある際、ご確認の程よろしくお願いいたします。

2021-02-19 23:11 UTC, shimotaroo approved these changes
バッチリです！
お疲れ様でした😁

2021-02-19 23:11 UTC, merged