add:ユーザー関係のマイグレーションファイル&シーダーファイル(ほくと)
quest-academia/yanbaru_ec_traning pull request #96
Opened 2021-03-16 14:05 UTC by tokuho0719

よろしくお願い致します。

2021-03-16 15:26 UTC, ziko7110 commented on database/migrations/2021_03_15_140102_create_m_users_table.php
> +            $table->string('password', 64);
各テーブルに主キーとなるidをつけて下さい！
```PHP
   $table->increments('id');
```

2021-03-16 15:26 UTC, ziko7110 commented on database/migrations/2021_03_15_140102_create_m_users_table.php
> +            $table->char('delete_flag', 1);
デリートフラグに関しては0か1で判断するので予め0にしておくのがいいですね
```PHP
 $table->char('delete_flag', 1)->default(0);
```

2021-03-16 15:26 UTC, ziko7110 commented on database/seeds/M_UsersTableSeeder.php
> +            'delete_flag' => '1'
```PHP
'delete_flag' => '1'
```
1で入れてしまうと削除された状態と認識されてしまいます。。
default値を0にしたので、なにも書かなくても動くと思います！

2021-03-17 14:05 UTC, tokuho0719 commented
@ziko7110 さん
添削頂きありがとうございます。
主キーと'delete_flag'修正致しました。

2021-03-17 14:38 UTC, ziko7110 commented
修正お疲れ様です！僕としてはLGTMです！
ゆーたろーさんに2次レビューお願いします！

2021-03-17 23:49 UTC, shimotaroo requested changes
レビューしました！
全体的によくできていますね！

外部キー制約用のコードだけ追記しておきましょう！

2021-03-17 23:49 UTC, shimotaroo commented on database/migrations/2021_03_15_140102_create_m_users_table.php
> +            $table->char('delete_flag', 1)->default(0); //デリートフラグ修正
本来はここに
**user_classification_idはm_user_classificationsのidが入るようにする**
という外部キー制約が必要となりますので、コードだけ追記しておきましょう！

プルリクエスト発行時は上記コードはコメントアウトしておいてOKです！

以下の記事を参考にしてみてください↓
https://readouble.com/laravel/5.8/ja/migrations.html#foreign-key-constraints

2021-03-18 13:35 UTC, tokuho0719 commented on database/migrations/2021_03_15_140102_create_m_users_table.php
> +            $table->char('delete_flag', 1)->default(0); //デリートフラグ修正
添削ありがとうございます。
外部キー制約追記しましたので、レビューよろしくお願い致します。

2021-03-18 13:40 UTC, tokuho0719 commented
添削ありがとうございます。
外部キー制約追記しましたので、レビューよろしくお願い致します。

2021-03-18 14:34 UTC, shimotaroo approved these changes
LGTMです〜！

ベストは
```
$table->foreign('user_classification_id')->references('id')->on('m_user_classifications')->onDelete('cascade');
```

ですが、頭に入れておくだけしておいてください！！

マージします！

2021-03-18 14:34 UTC, merged