add:仕入れ関係のマイグレーションファイル(Riki)
quest-academia/yanbaru_ec_traning pull request #98
Opened 2021-03-17 18:01 UTC by riki-ichikawa

レビューよろしくお願い致します。

2021-03-19 00:42 UTC, ziko7110 commented on database/migrations/2021_03_16_144201_create_purchases_table.php
> +            $table->timestamp('order_date')->nullable(false)->useCurrent();
```PHP
->nullable(false)
```
が不要ですね。
->nullable()で、nullを許可するのですが何もつけなければnullを許容しない設定です。

->nullable(false)はnull許可を解除するとき使います！

2021-03-19 16:23 UTC, riki-ichikawa commented
@ziko7110 さん
ご指摘ありがとうございます。
->nullable(false)は削除致しました。
nullを許容しない場合は->nullable(false)は必須と誤認識していました。

また、外部キー制約のコード追記しましたので、確認お願いします。

2021-03-19 23:25 UTC, shimotaroo requested changes
レビューしました！
あと少しです！！

2021-03-19 23:25 UTC, shimotaroo commented on database/migrations/2021_03_16_144201_create_purchases_table.php
> +            //$table->foreign('products_id')->references('id')->on(m_products)->onDelete('cascade');
ER図を見てカラム名があっているか確認してみましょう！

2021-03-19 23:25 UTC, shimotaroo commented on database/migrations/2021_03_16_144201_create_purchases_table.php
> +            $table->timestamp('purchase_date')->useCurrent();
`->useCurrent()`はデフォルト値設定のメソッドですが、そもそも2つのカラムはNULL許容してないので特に不要かと思います！
（今回は修正もしなくても良いです）

2021-03-20 01:11 UTC, riki-ichikawa commented on database/migrations/2021_03_16_144201_create_purchases_table.php
> +            //$table->foreign('products_id')->references('id')->on(m_products)->onDelete('cascade');
ご指摘ありがとうございます。
申し訳ございません、確認不足でした。
ER図確認して以下修正しました。
　products_id　→　product_id

2021-03-20 01:17 UTC, riki-ichikawa commented on database/migrations/2021_03_16_144201_create_purchases_table.php
> +            $table->timestamp('purchase_date')->useCurrent();
ご指摘ありがとうございます。
承知しました。
次回からデフォルト値設定の有無をよく確認します。

2021-03-20 01:52 UTC, shimotaroo approved these changes
LGTMです🥰

2021-03-20 01:53 UTC, merged