add:商品・カテゴリ・状態マイグレーションファイル作成
quest-academia/yanbaru_ec_traning pull request #99
Opened 2021-03-20 07:29 UTC by KawataTsutomu

遅れてしまい申し訳ありません。
ご確認宜しくお願いします。

2021-03-20 08:34 UTC, ziko7110 commented on database/migrations/2021_03_19_231951_create_m_products_table.php
> +            // $table->char('delete_flag', 1)->default(0);
delete_flagはコメントアウトしなくて良いと思います！
次回のforeignKey作成時に内容がブレるのでここで出来るかぎりカラムは作成しておきたいです。

2021-03-20 17:42 UTC, KawataTsutomu commented
ジーコさんレビューありがとうございます！
delete_flagコメントアウト修正しました。
ご確認宜しくお願いします。

2021-03-21 00:19 UTC, ziko7110 commented
確認致しました！LGTMです！＾＾

2021-03-21 04:32 UTC, shimotaroo requested changes
外部キー制約の概念の理解が少し足りてないかと思いますので、Qiitaなりドキュメントを調べてみてください！！

2021-03-21 04:32 UTC, shimotaroo commented on database/migrations/2021_03_19_231951_create_m_products_table.php
> +            // $table->foreign('category_id')->references('id')->on('m_categorles')->onDelete('cascade');
テーブル名間違えていますね！

2021-03-21 04:32 UTC, shimotaroo commented on database/migrations/2021_03_19_231951_create_m_products_table.php
> +            // $table->foreign('id')->references('product_id')->on('t_purchases')->onDelete('cascade');
このテーブルの`id`カラムは外部キーではなく、主キー（PK）なのでこの記載は不要ですね！
意味がよくわからなかったら質問くださいね！

2021-03-21 04:32 UTC, shimotaroo commented on database/migrations/2021_03_20_024833_create_m_categorles_table.php
> +        Schema::create('m_categorles', function (Blueprint $table) {
ファイル名もですが、テーブル名が違います！

2021-03-21 04:32 UTC, shimotaroo commented on database/migrations/2021_03_20_024833_create_m_categorles_table.php
> +            // $table->foreign('id')->references('category_id')->on('m_products')->onDelete('cascade');
`database/migrations/2021_03_19_231951_create_m_products_table.php`
へのコメントを同様です！

2021-03-21 04:32 UTC, shimotaroo commented on database/migrations/2021_03_20_025033_create_m_sale_statuses_table.php
> +            // $table->foreign('id')->references('sale_status_id')->on('m_products')->onDelete('cascade');
`database/migrations/2021_03_19_231951_create_m_products_table.php`
へのコメントを同様です！

2021-03-21 04:32 UTC, shimotaroo commented on database/migrations/2021_03_20_025426_create_m_product_statuses_table.php
> +            // $table->foreign('id')->references('product_status_id')->on('m_products')->onDelete('cascade');
`database/migrations/2021_03_19_231951_create_m_products_table.php`
へのコメントを同様です！

2021-03-21 15:05 UTC, KawataTsutomu commented
- 外部キー制約

- categorles→categories綴り修正

主要キーには書かなくていいのは理解できました。

2021-03-22 20:20 UTC, KawataTsutomu commented
シーダーファイル作成も入ってしまっていたので、`git revert`でひとつ戻してpushやり直しました。

2021-03-22 22:32 UTC, shimotaroo approved these changes
LGTMです😁
Git操作もバッチリです！！

2021-03-22 22:32 UTC, merged